/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kubernetes.client.kubevirt.models;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

/**
 * V1alpha3VirtualMachineInstanceSpecDomainDevicesInputs
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-11-29T01:55:00.032Z[Etc/UTC]")
public class V1alpha3VirtualMachineInstanceSpecDomainDevicesInputs {
  public static final String SERIALIZED_NAME_BUS = "bus";
  @SerializedName(SERIALIZED_NAME_BUS)
  private String bus;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private String type;


  public V1alpha3VirtualMachineInstanceSpecDomainDevicesInputs bus(String bus) {
    
    this.bus = bus;
    return this;
  }

   /**
   * Bus indicates the bus of input device to emulate. Supported values: virtio, usb.
   * @return bus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Bus indicates the bus of input device to emulate. Supported values: virtio, usb.")

  public String getBus() {
    return bus;
  }


  public void setBus(String bus) {
    this.bus = bus;
  }


  public V1alpha3VirtualMachineInstanceSpecDomainDevicesInputs name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Name is the device name
   * @return name
  **/
  @ApiModelProperty(required = true, value = "Name is the device name")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public V1alpha3VirtualMachineInstanceSpecDomainDevicesInputs type(String type) {
    
    this.type = type;
    return this;
  }

   /**
   * Type indicated the type of input device. Supported values: tablet.
   * @return type
  **/
  @ApiModelProperty(required = true, value = "Type indicated the type of input device. Supported values: tablet.")

  public String getType() {
    return type;
  }


  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha3VirtualMachineInstanceSpecDomainDevicesInputs v1alpha3VirtualMachineInstanceSpecDomainDevicesInputs = (V1alpha3VirtualMachineInstanceSpecDomainDevicesInputs) o;
    return Objects.equals(this.bus, v1alpha3VirtualMachineInstanceSpecDomainDevicesInputs.bus) &&
        Objects.equals(this.name, v1alpha3VirtualMachineInstanceSpecDomainDevicesInputs.name) &&
        Objects.equals(this.type, v1alpha3VirtualMachineInstanceSpecDomainDevicesInputs.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bus, name, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha3VirtualMachineInstanceSpecDomainDevicesInputs {\n");
    sb.append("    bus: ").append(toIndentedString(bus)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

