/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kubernetes.client.kubevirt.models;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * CloudInitNoCloud represents a cloud-init NoCloud user-data source. The NoCloud data will be added as a disk to the vmi. A proper cloud-init installation is required inside the guest. More info: http://cloudinit.readthedocs.io/en/latest/topics/datasources/nocloud.html
 */
@ApiModel(description = "CloudInitNoCloud represents a cloud-init NoCloud user-data source. The NoCloud data will be added as a disk to the vmi. A proper cloud-init installation is required inside the guest. More info: http://cloudinit.readthedocs.io/en/latest/topics/datasources/nocloud.html")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-11-29T01:55:00.032Z[Etc/UTC]")
public class V1alpha3VirtualMachineInstanceSpecCloudInitNoCloud {
  public static final String SERIALIZED_NAME_NETWORK_DATA = "networkData";
  @SerializedName(SERIALIZED_NAME_NETWORK_DATA)
  private String networkData;

  public static final String SERIALIZED_NAME_NETWORK_DATA_BASE64 = "networkDataBase64";
  @SerializedName(SERIALIZED_NAME_NETWORK_DATA_BASE64)
  private String networkDataBase64;

  public static final String SERIALIZED_NAME_NETWORK_DATA_SECRET_REF = "networkDataSecretRef";
  @SerializedName(SERIALIZED_NAME_NETWORK_DATA_SECRET_REF)
  private V1alpha3VirtualMachineInstanceSpecCloudInitNoCloudNetworkDataSecretRef networkDataSecretRef;

  public static final String SERIALIZED_NAME_SECRET_REF = "secretRef";
  @SerializedName(SERIALIZED_NAME_SECRET_REF)
  private V1alpha3VirtualMachineInstanceSpecCloudInitNoCloudSecretRef secretRef;

  public static final String SERIALIZED_NAME_USER_DATA = "userData";
  @SerializedName(SERIALIZED_NAME_USER_DATA)
  private String userData;

  public static final String SERIALIZED_NAME_USER_DATA_BASE64 = "userDataBase64";
  @SerializedName(SERIALIZED_NAME_USER_DATA_BASE64)
  private String userDataBase64;


  public V1alpha3VirtualMachineInstanceSpecCloudInitNoCloud networkData(String networkData) {
    
    this.networkData = networkData;
    return this;
  }

   /**
   * NetworkData contains NoCloud inline cloud-init networkdata.
   * @return networkData
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "NetworkData contains NoCloud inline cloud-init networkdata.")

  public String getNetworkData() {
    return networkData;
  }


  public void setNetworkData(String networkData) {
    this.networkData = networkData;
  }


  public V1alpha3VirtualMachineInstanceSpecCloudInitNoCloud networkDataBase64(String networkDataBase64) {
    
    this.networkDataBase64 = networkDataBase64;
    return this;
  }

   /**
   * NetworkDataBase64 contains NoCloud cloud-init networkdata as a base64 encoded string.
   * @return networkDataBase64
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "NetworkDataBase64 contains NoCloud cloud-init networkdata as a base64 encoded string.")

  public String getNetworkDataBase64() {
    return networkDataBase64;
  }


  public void setNetworkDataBase64(String networkDataBase64) {
    this.networkDataBase64 = networkDataBase64;
  }


  public V1alpha3VirtualMachineInstanceSpecCloudInitNoCloud networkDataSecretRef(V1alpha3VirtualMachineInstanceSpecCloudInitNoCloudNetworkDataSecretRef networkDataSecretRef) {
    
    this.networkDataSecretRef = networkDataSecretRef;
    return this;
  }

   /**
   * Get networkDataSecretRef
   * @return networkDataSecretRef
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha3VirtualMachineInstanceSpecCloudInitNoCloudNetworkDataSecretRef getNetworkDataSecretRef() {
    return networkDataSecretRef;
  }


  public void setNetworkDataSecretRef(V1alpha3VirtualMachineInstanceSpecCloudInitNoCloudNetworkDataSecretRef networkDataSecretRef) {
    this.networkDataSecretRef = networkDataSecretRef;
  }


  public V1alpha3VirtualMachineInstanceSpecCloudInitNoCloud secretRef(V1alpha3VirtualMachineInstanceSpecCloudInitNoCloudSecretRef secretRef) {
    
    this.secretRef = secretRef;
    return this;
  }

   /**
   * Get secretRef
   * @return secretRef
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha3VirtualMachineInstanceSpecCloudInitNoCloudSecretRef getSecretRef() {
    return secretRef;
  }


  public void setSecretRef(V1alpha3VirtualMachineInstanceSpecCloudInitNoCloudSecretRef secretRef) {
    this.secretRef = secretRef;
  }


  public V1alpha3VirtualMachineInstanceSpecCloudInitNoCloud userData(String userData) {
    
    this.userData = userData;
    return this;
  }

   /**
   * UserData contains NoCloud inline cloud-init userdata.
   * @return userData
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "UserData contains NoCloud inline cloud-init userdata.")

  public String getUserData() {
    return userData;
  }


  public void setUserData(String userData) {
    this.userData = userData;
  }


  public V1alpha3VirtualMachineInstanceSpecCloudInitNoCloud userDataBase64(String userDataBase64) {
    
    this.userDataBase64 = userDataBase64;
    return this;
  }

   /**
   * UserDataBase64 contains NoCloud cloud-init userdata as a base64 encoded string.
   * @return userDataBase64
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "UserDataBase64 contains NoCloud cloud-init userdata as a base64 encoded string.")

  public String getUserDataBase64() {
    return userDataBase64;
  }


  public void setUserDataBase64(String userDataBase64) {
    this.userDataBase64 = userDataBase64;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha3VirtualMachineInstanceSpecCloudInitNoCloud v1alpha3VirtualMachineInstanceSpecCloudInitNoCloud = (V1alpha3VirtualMachineInstanceSpecCloudInitNoCloud) o;
    return Objects.equals(this.networkData, v1alpha3VirtualMachineInstanceSpecCloudInitNoCloud.networkData) &&
        Objects.equals(this.networkDataBase64, v1alpha3VirtualMachineInstanceSpecCloudInitNoCloud.networkDataBase64) &&
        Objects.equals(this.networkDataSecretRef, v1alpha3VirtualMachineInstanceSpecCloudInitNoCloud.networkDataSecretRef) &&
        Objects.equals(this.secretRef, v1alpha3VirtualMachineInstanceSpecCloudInitNoCloud.secretRef) &&
        Objects.equals(this.userData, v1alpha3VirtualMachineInstanceSpecCloudInitNoCloud.userData) &&
        Objects.equals(this.userDataBase64, v1alpha3VirtualMachineInstanceSpecCloudInitNoCloud.userDataBase64);
  }

  @Override
  public int hashCode() {
    return Objects.hash(networkData, networkDataBase64, networkDataSecretRef, secretRef, userData, userDataBase64);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha3VirtualMachineInstanceSpecCloudInitNoCloud {\n");
    sb.append("    networkData: ").append(toIndentedString(networkData)).append("\n");
    sb.append("    networkDataBase64: ").append(toIndentedString(networkDataBase64)).append("\n");
    sb.append("    networkDataSecretRef: ").append(toIndentedString(networkDataSecretRef)).append("\n");
    sb.append("    secretRef: ").append(toIndentedString(secretRef)).append("\n");
    sb.append("    userData: ").append(toIndentedString(userData)).append("\n");
    sb.append("    userDataBase64: ").append(toIndentedString(userDataBase64)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

