/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kubernetes.client.kubevirt.models;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Clock sets the clock and timers of the vmi.
 */
@ApiModel(description = "Clock sets the clock and timers of the vmi.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-11-29T01:55:00.032Z[Etc/UTC]")
public class V1alpha3VirtualMachineInstanceSpecDomainClock {
  public static final String SERIALIZED_NAME_TIMER = "timer";
  @SerializedName(SERIALIZED_NAME_TIMER)
  private V1alpha3VirtualMachineInstanceSpecDomainClockTimer timer;

  public static final String SERIALIZED_NAME_TIMEZONE = "timezone";
  @SerializedName(SERIALIZED_NAME_TIMEZONE)
  private String timezone;

  public static final String SERIALIZED_NAME_UTC = "utc";
  @SerializedName(SERIALIZED_NAME_UTC)
  private V1alpha3VirtualMachineInstanceSpecDomainClockUtc utc;


  public V1alpha3VirtualMachineInstanceSpecDomainClock timer(V1alpha3VirtualMachineInstanceSpecDomainClockTimer timer) {
    
    this.timer = timer;
    return this;
  }

   /**
   * Get timer
   * @return timer
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha3VirtualMachineInstanceSpecDomainClockTimer getTimer() {
    return timer;
  }


  public void setTimer(V1alpha3VirtualMachineInstanceSpecDomainClockTimer timer) {
    this.timer = timer;
  }


  public V1alpha3VirtualMachineInstanceSpecDomainClock timezone(String timezone) {
    
    this.timezone = timezone;
    return this;
  }

   /**
   * Timezone sets the guest clock to the specified timezone. Zone name follows the TZ environment variable format (e.g. &#39;America/New_York&#39;).
   * @return timezone
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Timezone sets the guest clock to the specified timezone. Zone name follows the TZ environment variable format (e.g. 'America/New_York').")

  public String getTimezone() {
    return timezone;
  }


  public void setTimezone(String timezone) {
    this.timezone = timezone;
  }


  public V1alpha3VirtualMachineInstanceSpecDomainClock utc(V1alpha3VirtualMachineInstanceSpecDomainClockUtc utc) {
    
    this.utc = utc;
    return this;
  }

   /**
   * Get utc
   * @return utc
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha3VirtualMachineInstanceSpecDomainClockUtc getUtc() {
    return utc;
  }


  public void setUtc(V1alpha3VirtualMachineInstanceSpecDomainClockUtc utc) {
    this.utc = utc;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha3VirtualMachineInstanceSpecDomainClock v1alpha3VirtualMachineInstanceSpecDomainClock = (V1alpha3VirtualMachineInstanceSpecDomainClock) o;
    return Objects.equals(this.timer, v1alpha3VirtualMachineInstanceSpecDomainClock.timer) &&
        Objects.equals(this.timezone, v1alpha3VirtualMachineInstanceSpecDomainClock.timezone) &&
        Objects.equals(this.utc, v1alpha3VirtualMachineInstanceSpecDomainClock.utc);
  }

  @Override
  public int hashCode() {
    return Objects.hash(timer, timezone, utc);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha3VirtualMachineInstanceSpecDomainClock {\n");
    sb.append("    timer: ").append(toIndentedString(timer)).append("\n");
    sb.append("    timezone: ").append(toIndentedString(timezone)).append("\n");
    sb.append("    utc: ").append(toIndentedString(utc)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

