/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kubernetes.client.kubevirt.models;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Features like acpi, apic, hyperv, smm.
 */
@ApiModel(description = "Features like acpi, apic, hyperv, smm.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-11-29T01:55:00.032Z[Etc/UTC]")
public class V1alpha3VirtualMachineInstanceSpecDomainFeatures {
  public static final String SERIALIZED_NAME_ACPI = "acpi";
  @SerializedName(SERIALIZED_NAME_ACPI)
  private V1alpha3VirtualMachineInstanceSpecDomainFeaturesAcpi acpi;

  public static final String SERIALIZED_NAME_APIC = "apic";
  @SerializedName(SERIALIZED_NAME_APIC)
  private V1alpha3VirtualMachineInstanceSpecDomainFeaturesApic apic;

  public static final String SERIALIZED_NAME_HYPERV = "hyperv";
  @SerializedName(SERIALIZED_NAME_HYPERV)
  private V1alpha3VirtualMachineInstanceSpecDomainFeaturesHyperv hyperv;

  public static final String SERIALIZED_NAME_KVM = "kvm";
  @SerializedName(SERIALIZED_NAME_KVM)
  private V1alpha3VirtualMachineInstanceSpecDomainFeaturesKvm kvm;

  public static final String SERIALIZED_NAME_SMM = "smm";
  @SerializedName(SERIALIZED_NAME_SMM)
  private V1alpha3VirtualMachineInstanceSpecDomainFeaturesSmm smm;


  public V1alpha3VirtualMachineInstanceSpecDomainFeatures acpi(V1alpha3VirtualMachineInstanceSpecDomainFeaturesAcpi acpi) {
    
    this.acpi = acpi;
    return this;
  }

   /**
   * Get acpi
   * @return acpi
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha3VirtualMachineInstanceSpecDomainFeaturesAcpi getAcpi() {
    return acpi;
  }


  public void setAcpi(V1alpha3VirtualMachineInstanceSpecDomainFeaturesAcpi acpi) {
    this.acpi = acpi;
  }


  public V1alpha3VirtualMachineInstanceSpecDomainFeatures apic(V1alpha3VirtualMachineInstanceSpecDomainFeaturesApic apic) {
    
    this.apic = apic;
    return this;
  }

   /**
   * Get apic
   * @return apic
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha3VirtualMachineInstanceSpecDomainFeaturesApic getApic() {
    return apic;
  }


  public void setApic(V1alpha3VirtualMachineInstanceSpecDomainFeaturesApic apic) {
    this.apic = apic;
  }


  public V1alpha3VirtualMachineInstanceSpecDomainFeatures hyperv(V1alpha3VirtualMachineInstanceSpecDomainFeaturesHyperv hyperv) {
    
    this.hyperv = hyperv;
    return this;
  }

   /**
   * Get hyperv
   * @return hyperv
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha3VirtualMachineInstanceSpecDomainFeaturesHyperv getHyperv() {
    return hyperv;
  }


  public void setHyperv(V1alpha3VirtualMachineInstanceSpecDomainFeaturesHyperv hyperv) {
    this.hyperv = hyperv;
  }


  public V1alpha3VirtualMachineInstanceSpecDomainFeatures kvm(V1alpha3VirtualMachineInstanceSpecDomainFeaturesKvm kvm) {
    
    this.kvm = kvm;
    return this;
  }

   /**
   * Get kvm
   * @return kvm
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha3VirtualMachineInstanceSpecDomainFeaturesKvm getKvm() {
    return kvm;
  }


  public void setKvm(V1alpha3VirtualMachineInstanceSpecDomainFeaturesKvm kvm) {
    this.kvm = kvm;
  }


  public V1alpha3VirtualMachineInstanceSpecDomainFeatures smm(V1alpha3VirtualMachineInstanceSpecDomainFeaturesSmm smm) {
    
    this.smm = smm;
    return this;
  }

   /**
   * Get smm
   * @return smm
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha3VirtualMachineInstanceSpecDomainFeaturesSmm getSmm() {
    return smm;
  }


  public void setSmm(V1alpha3VirtualMachineInstanceSpecDomainFeaturesSmm smm) {
    this.smm = smm;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha3VirtualMachineInstanceSpecDomainFeatures v1alpha3VirtualMachineInstanceSpecDomainFeatures = (V1alpha3VirtualMachineInstanceSpecDomainFeatures) o;
    return Objects.equals(this.acpi, v1alpha3VirtualMachineInstanceSpecDomainFeatures.acpi) &&
        Objects.equals(this.apic, v1alpha3VirtualMachineInstanceSpecDomainFeatures.apic) &&
        Objects.equals(this.hyperv, v1alpha3VirtualMachineInstanceSpecDomainFeatures.hyperv) &&
        Objects.equals(this.kvm, v1alpha3VirtualMachineInstanceSpecDomainFeatures.kvm) &&
        Objects.equals(this.smm, v1alpha3VirtualMachineInstanceSpecDomainFeatures.smm);
  }

  @Override
  public int hashCode() {
    return Objects.hash(acpi, apic, hyperv, kvm, smm);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha3VirtualMachineInstanceSpecDomainFeatures {\n");
    sb.append("    acpi: ").append(toIndentedString(acpi)).append("\n");
    sb.append("    apic: ").append(toIndentedString(apic)).append("\n");
    sb.append("    hyperv: ").append(toIndentedString(hyperv)).append("\n");
    sb.append("    kvm: ").append(toIndentedString(kvm)).append("\n");
    sb.append("    smm: ").append(toIndentedString(smm)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

