/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kubernetes.client.kubevirt.models;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * HPET (High Precision Event Timer) - multiple timers with periodic interrupts.
 */
@ApiModel(description = "HPET (High Precision Event Timer) - multiple timers with periodic interrupts.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-11-29T01:55:00.032Z[Etc/UTC]")
public class V1alpha3VirtualMachineInstanceSpecDomainClockTimerHpet {
  public static final String SERIALIZED_NAME_PRESENT = "present";
  @SerializedName(SERIALIZED_NAME_PRESENT)
  private Boolean present;

  public static final String SERIALIZED_NAME_TICK_POLICY = "tickPolicy";
  @SerializedName(SERIALIZED_NAME_TICK_POLICY)
  private String tickPolicy;


  public V1alpha3VirtualMachineInstanceSpecDomainClockTimerHpet present(Boolean present) {
    
    this.present = present;
    return this;
  }

   /**
   * Enabled set to false makes sure that the machine type or a preset can&#39;t add the timer. Defaults to true.
   * @return present
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Enabled set to false makes sure that the machine type or a preset can't add the timer. Defaults to true.")

  public Boolean getPresent() {
    return present;
  }


  public void setPresent(Boolean present) {
    this.present = present;
  }


  public V1alpha3VirtualMachineInstanceSpecDomainClockTimerHpet tickPolicy(String tickPolicy) {
    
    this.tickPolicy = tickPolicy;
    return this;
  }

   /**
   * TickPolicy determines what happens when QEMU misses a deadline for injecting a tick to the guest. One of \&quot;delay\&quot;, \&quot;catchup\&quot;, \&quot;merge\&quot;, \&quot;discard\&quot;.
   * @return tickPolicy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "TickPolicy determines what happens when QEMU misses a deadline for injecting a tick to the guest. One of \"delay\", \"catchup\", \"merge\", \"discard\".")

  public String getTickPolicy() {
    return tickPolicy;
  }


  public void setTickPolicy(String tickPolicy) {
    this.tickPolicy = tickPolicy;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha3VirtualMachineInstanceSpecDomainClockTimerHpet v1alpha3VirtualMachineInstanceSpecDomainClockTimerHpet = (V1alpha3VirtualMachineInstanceSpecDomainClockTimerHpet) o;
    return Objects.equals(this.present, v1alpha3VirtualMachineInstanceSpecDomainClockTimerHpet.present) &&
        Objects.equals(this.tickPolicy, v1alpha3VirtualMachineInstanceSpecDomainClockTimerHpet.tickPolicy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(present, tickPolicy);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha3VirtualMachineInstanceSpecDomainClockTimerHpet {\n");
    sb.append("    present: ").append(toIndentedString(present)).append("\n");
    sb.append("    tickPolicy: ").append(toIndentedString(tickPolicy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

