/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kubernetes.client.kubevirt.models;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Represents the multus cni network.
 */
@ApiModel(description = "Represents the multus cni network.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-11-29T01:55:00.032Z[Etc/UTC]")
public class V1alpha3VirtualMachineInstanceSpecMultus {
  public static final String SERIALIZED_NAME_DEFAULT = "default";
  @SerializedName(SERIALIZED_NAME_DEFAULT)
  private Boolean _default;

  public static final String SERIALIZED_NAME_NETWORK_NAME = "networkName";
  @SerializedName(SERIALIZED_NAME_NETWORK_NAME)
  private String networkName;


  public V1alpha3VirtualMachineInstanceSpecMultus _default(Boolean _default) {
    
    this._default = _default;
    return this;
  }

   /**
   * Select the default network and add it to the multus-cni.io/default-network annotation.
   * @return _default
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Select the default network and add it to the multus-cni.io/default-network annotation.")

  public Boolean getDefault() {
    return _default;
  }


  public void setDefault(Boolean _default) {
    this._default = _default;
  }


  public V1alpha3VirtualMachineInstanceSpecMultus networkName(String networkName) {
    
    this.networkName = networkName;
    return this;
  }

   /**
   * References to a NetworkAttachmentDefinition CRD object. Format: &lt;networkName&gt;, &lt;namespace&gt;/&lt;networkName&gt;. If namespace is not specified, VMI namespace is assumed.
   * @return networkName
  **/
  @ApiModelProperty(required = true, value = "References to a NetworkAttachmentDefinition CRD object. Format: <networkName>, <namespace>/<networkName>. If namespace is not specified, VMI namespace is assumed.")

  public String getNetworkName() {
    return networkName;
  }


  public void setNetworkName(String networkName) {
    this.networkName = networkName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha3VirtualMachineInstanceSpecMultus v1alpha3VirtualMachineInstanceSpecMultus = (V1alpha3VirtualMachineInstanceSpecMultus) o;
    return Objects.equals(this._default, v1alpha3VirtualMachineInstanceSpecMultus._default) &&
        Objects.equals(this.networkName, v1alpha3VirtualMachineInstanceSpecMultus.networkName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_default, networkName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha3VirtualMachineInstanceSpecMultus {\n");
    sb.append("    _default: ").append(toIndentedString(_default)).append("\n");
    sb.append("    networkName: ").append(toIndentedString(networkName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

