/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kubernetes.client.kubevirt.models;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * i6300esb watchdog device.
 */
@ApiModel(description = "i6300esb watchdog device.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-11-29T01:55:00.032Z[Etc/UTC]")
public class V1alpha3VirtualMachineInstanceSpecDomainDevicesWatchdogI6300esb {
  public static final String SERIALIZED_NAME_ACTION = "action";
  @SerializedName(SERIALIZED_NAME_ACTION)
  private String action;


  public V1alpha3VirtualMachineInstanceSpecDomainDevicesWatchdogI6300esb action(String action) {
    
    this.action = action;
    return this;
  }

   /**
   * The action to take. Valid values are poweroff, reset, shutdown. Defaults to reset.
   * @return action
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The action to take. Valid values are poweroff, reset, shutdown. Defaults to reset.")

  public String getAction() {
    return action;
  }


  public void setAction(String action) {
    this.action = action;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha3VirtualMachineInstanceSpecDomainDevicesWatchdogI6300esb v1alpha3VirtualMachineInstanceSpecDomainDevicesWatchdogI6300esb = (V1alpha3VirtualMachineInstanceSpecDomainDevicesWatchdogI6300esb) o;
    return Objects.equals(this.action, v1alpha3VirtualMachineInstanceSpecDomainDevicesWatchdogI6300esb.action);
  }

  @Override
  public int hashCode() {
    return Objects.hash(action);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha3VirtualMachineInstanceSpecDomainDevicesWatchdogI6300esb {\n");
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

