/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kubernetes.client.kubevirt.models;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * If set (default), BIOS will be used.
 */
@ApiModel(description = "If set (default), BIOS will be used.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-11-29T01:55:00.032Z[Etc/UTC]")
public class V1alpha3VirtualMachineInstanceSpecDomainFirmwareBootloaderBios {
  public static final String SERIALIZED_NAME_USE_SERIAL = "useSerial";
  @SerializedName(SERIALIZED_NAME_USE_SERIAL)
  private Boolean useSerial;


  public V1alpha3VirtualMachineInstanceSpecDomainFirmwareBootloaderBios useSerial(Boolean useSerial) {
    
    this.useSerial = useSerial;
    return this;
  }

   /**
   * If set, the BIOS output will be transmitted over serial
   * @return useSerial
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "If set, the BIOS output will be transmitted over serial")

  public Boolean getUseSerial() {
    return useSerial;
  }


  public void setUseSerial(Boolean useSerial) {
    this.useSerial = useSerial;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha3VirtualMachineInstanceSpecDomainFirmwareBootloaderBios v1alpha3VirtualMachineInstanceSpecDomainFirmwareBootloaderBios = (V1alpha3VirtualMachineInstanceSpecDomainFirmwareBootloaderBios) o;
    return Objects.equals(this.useSerial, v1alpha3VirtualMachineInstanceSpecDomainFirmwareBootloaderBios.useSerial);
  }

  @Override
  public int hashCode() {
    return Objects.hash(useSerial);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha3VirtualMachineInstanceSpecDomainFirmwareBootloaderBios {\n");
    sb.append("    useSerial: ").append(toIndentedString(useSerial)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

