/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kubernetes.client.kubevirt.models;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * HTTPHeader describes a custom header to be used in HTTP probes
 */
@ApiModel(description = "HTTPHeader describes a custom header to be used in HTTP probes")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-11-29T01:55:00.032Z[Etc/UTC]")
public class V1alpha3VirtualMachineInstanceSpecLivenessProbeHttpGetHttpHeaders {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_VALUE = "value";
  @SerializedName(SERIALIZED_NAME_VALUE)
  private String value;


  public V1alpha3VirtualMachineInstanceSpecLivenessProbeHttpGetHttpHeaders name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * The header field name
   * @return name
  **/
  @ApiModelProperty(required = true, value = "The header field name")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public V1alpha3VirtualMachineInstanceSpecLivenessProbeHttpGetHttpHeaders value(String value) {
    
    this.value = value;
    return this;
  }

   /**
   * The header field value
   * @return value
  **/
  @ApiModelProperty(required = true, value = "The header field value")

  public String getValue() {
    return value;
  }


  public void setValue(String value) {
    this.value = value;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha3VirtualMachineInstanceSpecLivenessProbeHttpGetHttpHeaders v1alpha3VirtualMachineInstanceSpecLivenessProbeHttpGetHttpHeaders = (V1alpha3VirtualMachineInstanceSpecLivenessProbeHttpGetHttpHeaders) o;
    return Objects.equals(this.name, v1alpha3VirtualMachineInstanceSpecLivenessProbeHttpGetHttpHeaders.name) &&
        Objects.equals(this.value, v1alpha3VirtualMachineInstanceSpecLivenessProbeHttpGetHttpHeaders.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha3VirtualMachineInstanceSpecLivenessProbeHttpGetHttpHeaders {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

