/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kubernetes.client.kubevirt.models;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Port repesents a port to expose from the virtual machine. Default protocol TCP. The port field is mandatory
 */
@ApiModel(description = "Port repesents a port to expose from the virtual machine. Default protocol TCP. The port field is mandatory")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-11-29T01:55:00.032Z[Etc/UTC]")
public class V1alpha3VirtualMachineInstanceSpecDomainDevicesPorts {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_PORT = "port";
  @SerializedName(SERIALIZED_NAME_PORT)
  private Integer port;

  public static final String SERIALIZED_NAME_PROTOCOL = "protocol";
  @SerializedName(SERIALIZED_NAME_PROTOCOL)
  private String protocol;


  public V1alpha3VirtualMachineInstanceSpecDomainDevicesPorts name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * If specified, this must be an IANA_SVC_NAME and unique within the pod. Each named port in a pod must have a unique name. Name for the port that can be referred to by services.
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "If specified, this must be an IANA_SVC_NAME and unique within the pod. Each named port in a pod must have a unique name. Name for the port that can be referred to by services.")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public V1alpha3VirtualMachineInstanceSpecDomainDevicesPorts port(Integer port) {
    
    this.port = port;
    return this;
  }

   /**
   * Number of port to expose for the virtual machine. This must be a valid port number, 0 &lt; x &lt; 65536.
   * @return port
  **/
  @ApiModelProperty(required = true, value = "Number of port to expose for the virtual machine. This must be a valid port number, 0 < x < 65536.")

  public Integer getPort() {
    return port;
  }


  public void setPort(Integer port) {
    this.port = port;
  }


  public V1alpha3VirtualMachineInstanceSpecDomainDevicesPorts protocol(String protocol) {
    
    this.protocol = protocol;
    return this;
  }

   /**
   * Protocol for port. Must be UDP or TCP. Defaults to \&quot;TCP\&quot;.
   * @return protocol
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Protocol for port. Must be UDP or TCP. Defaults to \"TCP\".")

  public String getProtocol() {
    return protocol;
  }


  public void setProtocol(String protocol) {
    this.protocol = protocol;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha3VirtualMachineInstanceSpecDomainDevicesPorts v1alpha3VirtualMachineInstanceSpecDomainDevicesPorts = (V1alpha3VirtualMachineInstanceSpecDomainDevicesPorts) o;
    return Objects.equals(this.name, v1alpha3VirtualMachineInstanceSpecDomainDevicesPorts.name) &&
        Objects.equals(this.port, v1alpha3VirtualMachineInstanceSpecDomainDevicesPorts.port) &&
        Objects.equals(this.protocol, v1alpha3VirtualMachineInstanceSpecDomainDevicesPorts.protocol);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, port, protocol);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha3VirtualMachineInstanceSpecDomainDevicesPorts {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    port: ").append(toIndentedString(port)).append("\n");
    sb.append("    protocol: ").append(toIndentedString(protocol)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

