/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kubernetes.client.kubevirt.models;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Guest OS Information
 */
@ApiModel(description = "Guest OS Information")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-11-29T01:55:00.032Z[Etc/UTC]")
public class V1alpha3VirtualMachineInstanceStatusGuestOSInfo {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_KERNEL_RELEASE = "kernelRelease";
  @SerializedName(SERIALIZED_NAME_KERNEL_RELEASE)
  private String kernelRelease;

  public static final String SERIALIZED_NAME_KERNEL_VERSION = "kernelVersion";
  @SerializedName(SERIALIZED_NAME_KERNEL_VERSION)
  private String kernelVersion;

  public static final String SERIALIZED_NAME_MACHINE = "machine";
  @SerializedName(SERIALIZED_NAME_MACHINE)
  private String machine;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_PRETTY_NAME = "prettyName";
  @SerializedName(SERIALIZED_NAME_PRETTY_NAME)
  private String prettyName;

  public static final String SERIALIZED_NAME_VERSION = "version";
  @SerializedName(SERIALIZED_NAME_VERSION)
  private String version;

  public static final String SERIALIZED_NAME_VERSION_ID = "versionId";
  @SerializedName(SERIALIZED_NAME_VERSION_ID)
  private String versionId;


  public V1alpha3VirtualMachineInstanceStatusGuestOSInfo id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Guest OS Id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Guest OS Id")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public V1alpha3VirtualMachineInstanceStatusGuestOSInfo kernelRelease(String kernelRelease) {
    
    this.kernelRelease = kernelRelease;
    return this;
  }

   /**
   * Guest OS Kernel Release
   * @return kernelRelease
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Guest OS Kernel Release")

  public String getKernelRelease() {
    return kernelRelease;
  }


  public void setKernelRelease(String kernelRelease) {
    this.kernelRelease = kernelRelease;
  }


  public V1alpha3VirtualMachineInstanceStatusGuestOSInfo kernelVersion(String kernelVersion) {
    
    this.kernelVersion = kernelVersion;
    return this;
  }

   /**
   * Kernel version of the Guest OS
   * @return kernelVersion
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Kernel version of the Guest OS")

  public String getKernelVersion() {
    return kernelVersion;
  }


  public void setKernelVersion(String kernelVersion) {
    this.kernelVersion = kernelVersion;
  }


  public V1alpha3VirtualMachineInstanceStatusGuestOSInfo machine(String machine) {
    
    this.machine = machine;
    return this;
  }

   /**
   * Machine type of the Guest OS
   * @return machine
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Machine type of the Guest OS")

  public String getMachine() {
    return machine;
  }


  public void setMachine(String machine) {
    this.machine = machine;
  }


  public V1alpha3VirtualMachineInstanceStatusGuestOSInfo name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Name of the Guest OS
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Name of the Guest OS")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public V1alpha3VirtualMachineInstanceStatusGuestOSInfo prettyName(String prettyName) {
    
    this.prettyName = prettyName;
    return this;
  }

   /**
   * Guest OS Pretty Name
   * @return prettyName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Guest OS Pretty Name")

  public String getPrettyName() {
    return prettyName;
  }


  public void setPrettyName(String prettyName) {
    this.prettyName = prettyName;
  }


  public V1alpha3VirtualMachineInstanceStatusGuestOSInfo version(String version) {
    
    this.version = version;
    return this;
  }

   /**
   * Guest OS Version
   * @return version
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Guest OS Version")

  public String getVersion() {
    return version;
  }


  public void setVersion(String version) {
    this.version = version;
  }


  public V1alpha3VirtualMachineInstanceStatusGuestOSInfo versionId(String versionId) {
    
    this.versionId = versionId;
    return this;
  }

   /**
   * Version ID of the Guest OS
   * @return versionId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Version ID of the Guest OS")

  public String getVersionId() {
    return versionId;
  }


  public void setVersionId(String versionId) {
    this.versionId = versionId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha3VirtualMachineInstanceStatusGuestOSInfo v1alpha3VirtualMachineInstanceStatusGuestOSInfo = (V1alpha3VirtualMachineInstanceStatusGuestOSInfo) o;
    return Objects.equals(this.id, v1alpha3VirtualMachineInstanceStatusGuestOSInfo.id) &&
        Objects.equals(this.kernelRelease, v1alpha3VirtualMachineInstanceStatusGuestOSInfo.kernelRelease) &&
        Objects.equals(this.kernelVersion, v1alpha3VirtualMachineInstanceStatusGuestOSInfo.kernelVersion) &&
        Objects.equals(this.machine, v1alpha3VirtualMachineInstanceStatusGuestOSInfo.machine) &&
        Objects.equals(this.name, v1alpha3VirtualMachineInstanceStatusGuestOSInfo.name) &&
        Objects.equals(this.prettyName, v1alpha3VirtualMachineInstanceStatusGuestOSInfo.prettyName) &&
        Objects.equals(this.version, v1alpha3VirtualMachineInstanceStatusGuestOSInfo.version) &&
        Objects.equals(this.versionId, v1alpha3VirtualMachineInstanceStatusGuestOSInfo.versionId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, kernelRelease, kernelVersion, machine, name, prettyName, version, versionId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha3VirtualMachineInstanceStatusGuestOSInfo {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    kernelRelease: ").append(toIndentedString(kernelRelease)).append("\n");
    sb.append("    kernelVersion: ").append(toIndentedString(kernelVersion)).append("\n");
    sb.append("    machine: ").append(toIndentedString(machine)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    prettyName: ").append(toIndentedString(prettyName)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    versionId: ").append(toIndentedString(versionId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

