/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kubernetes.client.kubevirt.models;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Defaults to the machine type setting.
 */
@ApiModel(description = "Defaults to the machine type setting.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-11-29T01:55:00.032Z[Etc/UTC]")
public class V1alpha3VirtualMachineInstanceSpecDomainFeaturesHyperv {
  public static final String SERIALIZED_NAME_EVMCS = "evmcs";
  @SerializedName(SERIALIZED_NAME_EVMCS)
  private V1alpha3VirtualMachineInstanceSpecDomainFeaturesHypervEvmcs evmcs;

  public static final String SERIALIZED_NAME_FREQUENCIES = "frequencies";
  @SerializedName(SERIALIZED_NAME_FREQUENCIES)
  private V1alpha3VirtualMachineInstanceSpecDomainFeaturesHypervFrequencies frequencies;

  public static final String SERIALIZED_NAME_IPI = "ipi";
  @SerializedName(SERIALIZED_NAME_IPI)
  private V1alpha3VirtualMachineInstanceSpecDomainFeaturesHypervIpi ipi;

  public static final String SERIALIZED_NAME_REENLIGHTENMENT = "reenlightenment";
  @SerializedName(SERIALIZED_NAME_REENLIGHTENMENT)
  private V1alpha3VirtualMachineInstanceSpecDomainFeaturesHypervReenlightenment reenlightenment;

  public static final String SERIALIZED_NAME_RELAXED = "relaxed";
  @SerializedName(SERIALIZED_NAME_RELAXED)
  private V1alpha3VirtualMachineInstanceSpecDomainFeaturesHypervRelaxed relaxed;

  public static final String SERIALIZED_NAME_RESET = "reset";
  @SerializedName(SERIALIZED_NAME_RESET)
  private V1alpha3VirtualMachineInstanceSpecDomainFeaturesHypervReset reset;

  public static final String SERIALIZED_NAME_RUNTIME = "runtime";
  @SerializedName(SERIALIZED_NAME_RUNTIME)
  private V1alpha3VirtualMachineInstanceSpecDomainFeaturesHypervRuntime runtime;

  public static final String SERIALIZED_NAME_SPINLOCKS = "spinlocks";
  @SerializedName(SERIALIZED_NAME_SPINLOCKS)
  private V1alpha3VirtualMachineInstanceSpecDomainFeaturesHypervSpinlocks spinlocks;

  public static final String SERIALIZED_NAME_SYNIC = "synic";
  @SerializedName(SERIALIZED_NAME_SYNIC)
  private V1alpha3VirtualMachineInstanceSpecDomainFeaturesHypervSynic synic;

  public static final String SERIALIZED_NAME_SYNICTIMER = "synictimer";
  @SerializedName(SERIALIZED_NAME_SYNICTIMER)
  private V1alpha3VirtualMachineInstanceSpecDomainFeaturesHypervSynictimer synictimer;

  public static final String SERIALIZED_NAME_TLBFLUSH = "tlbflush";
  @SerializedName(SERIALIZED_NAME_TLBFLUSH)
  private V1alpha3VirtualMachineInstanceSpecDomainFeaturesHypervTlbflush tlbflush;

  public static final String SERIALIZED_NAME_VAPIC = "vapic";
  @SerializedName(SERIALIZED_NAME_VAPIC)
  private V1alpha3VirtualMachineInstanceSpecDomainFeaturesHypervVapic vapic;

  public static final String SERIALIZED_NAME_VENDORID = "vendorid";
  @SerializedName(SERIALIZED_NAME_VENDORID)
  private V1alpha3VirtualMachineInstanceSpecDomainFeaturesHypervVendorid vendorid;

  public static final String SERIALIZED_NAME_VPINDEX = "vpindex";
  @SerializedName(SERIALIZED_NAME_VPINDEX)
  private V1alpha3VirtualMachineInstanceSpecDomainFeaturesHypervVpindex vpindex;


  public V1alpha3VirtualMachineInstanceSpecDomainFeaturesHyperv evmcs(V1alpha3VirtualMachineInstanceSpecDomainFeaturesHypervEvmcs evmcs) {
    
    this.evmcs = evmcs;
    return this;
  }

   /**
   * Get evmcs
   * @return evmcs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha3VirtualMachineInstanceSpecDomainFeaturesHypervEvmcs getEvmcs() {
    return evmcs;
  }


  public void setEvmcs(V1alpha3VirtualMachineInstanceSpecDomainFeaturesHypervEvmcs evmcs) {
    this.evmcs = evmcs;
  }


  public V1alpha3VirtualMachineInstanceSpecDomainFeaturesHyperv frequencies(V1alpha3VirtualMachineInstanceSpecDomainFeaturesHypervFrequencies frequencies) {
    
    this.frequencies = frequencies;
    return this;
  }

   /**
   * Get frequencies
   * @return frequencies
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha3VirtualMachineInstanceSpecDomainFeaturesHypervFrequencies getFrequencies() {
    return frequencies;
  }


  public void setFrequencies(V1alpha3VirtualMachineInstanceSpecDomainFeaturesHypervFrequencies frequencies) {
    this.frequencies = frequencies;
  }


  public V1alpha3VirtualMachineInstanceSpecDomainFeaturesHyperv ipi(V1alpha3VirtualMachineInstanceSpecDomainFeaturesHypervIpi ipi) {
    
    this.ipi = ipi;
    return this;
  }

   /**
   * Get ipi
   * @return ipi
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha3VirtualMachineInstanceSpecDomainFeaturesHypervIpi getIpi() {
    return ipi;
  }


  public void setIpi(V1alpha3VirtualMachineInstanceSpecDomainFeaturesHypervIpi ipi) {
    this.ipi = ipi;
  }


  public V1alpha3VirtualMachineInstanceSpecDomainFeaturesHyperv reenlightenment(V1alpha3VirtualMachineInstanceSpecDomainFeaturesHypervReenlightenment reenlightenment) {
    
    this.reenlightenment = reenlightenment;
    return this;
  }

   /**
   * Get reenlightenment
   * @return reenlightenment
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha3VirtualMachineInstanceSpecDomainFeaturesHypervReenlightenment getReenlightenment() {
    return reenlightenment;
  }


  public void setReenlightenment(V1alpha3VirtualMachineInstanceSpecDomainFeaturesHypervReenlightenment reenlightenment) {
    this.reenlightenment = reenlightenment;
  }


  public V1alpha3VirtualMachineInstanceSpecDomainFeaturesHyperv relaxed(V1alpha3VirtualMachineInstanceSpecDomainFeaturesHypervRelaxed relaxed) {
    
    this.relaxed = relaxed;
    return this;
  }

   /**
   * Get relaxed
   * @return relaxed
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha3VirtualMachineInstanceSpecDomainFeaturesHypervRelaxed getRelaxed() {
    return relaxed;
  }


  public void setRelaxed(V1alpha3VirtualMachineInstanceSpecDomainFeaturesHypervRelaxed relaxed) {
    this.relaxed = relaxed;
  }


  public V1alpha3VirtualMachineInstanceSpecDomainFeaturesHyperv reset(V1alpha3VirtualMachineInstanceSpecDomainFeaturesHypervReset reset) {
    
    this.reset = reset;
    return this;
  }

   /**
   * Get reset
   * @return reset
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha3VirtualMachineInstanceSpecDomainFeaturesHypervReset getReset() {
    return reset;
  }


  public void setReset(V1alpha3VirtualMachineInstanceSpecDomainFeaturesHypervReset reset) {
    this.reset = reset;
  }


  public V1alpha3VirtualMachineInstanceSpecDomainFeaturesHyperv runtime(V1alpha3VirtualMachineInstanceSpecDomainFeaturesHypervRuntime runtime) {
    
    this.runtime = runtime;
    return this;
  }

   /**
   * Get runtime
   * @return runtime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha3VirtualMachineInstanceSpecDomainFeaturesHypervRuntime getRuntime() {
    return runtime;
  }


  public void setRuntime(V1alpha3VirtualMachineInstanceSpecDomainFeaturesHypervRuntime runtime) {
    this.runtime = runtime;
  }


  public V1alpha3VirtualMachineInstanceSpecDomainFeaturesHyperv spinlocks(V1alpha3VirtualMachineInstanceSpecDomainFeaturesHypervSpinlocks spinlocks) {
    
    this.spinlocks = spinlocks;
    return this;
  }

   /**
   * Get spinlocks
   * @return spinlocks
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha3VirtualMachineInstanceSpecDomainFeaturesHypervSpinlocks getSpinlocks() {
    return spinlocks;
  }


  public void setSpinlocks(V1alpha3VirtualMachineInstanceSpecDomainFeaturesHypervSpinlocks spinlocks) {
    this.spinlocks = spinlocks;
  }


  public V1alpha3VirtualMachineInstanceSpecDomainFeaturesHyperv synic(V1alpha3VirtualMachineInstanceSpecDomainFeaturesHypervSynic synic) {
    
    this.synic = synic;
    return this;
  }

   /**
   * Get synic
   * @return synic
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha3VirtualMachineInstanceSpecDomainFeaturesHypervSynic getSynic() {
    return synic;
  }


  public void setSynic(V1alpha3VirtualMachineInstanceSpecDomainFeaturesHypervSynic synic) {
    this.synic = synic;
  }


  public V1alpha3VirtualMachineInstanceSpecDomainFeaturesHyperv synictimer(V1alpha3VirtualMachineInstanceSpecDomainFeaturesHypervSynictimer synictimer) {
    
    this.synictimer = synictimer;
    return this;
  }

   /**
   * Get synictimer
   * @return synictimer
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha3VirtualMachineInstanceSpecDomainFeaturesHypervSynictimer getSynictimer() {
    return synictimer;
  }


  public void setSynictimer(V1alpha3VirtualMachineInstanceSpecDomainFeaturesHypervSynictimer synictimer) {
    this.synictimer = synictimer;
  }


  public V1alpha3VirtualMachineInstanceSpecDomainFeaturesHyperv tlbflush(V1alpha3VirtualMachineInstanceSpecDomainFeaturesHypervTlbflush tlbflush) {
    
    this.tlbflush = tlbflush;
    return this;
  }

   /**
   * Get tlbflush
   * @return tlbflush
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha3VirtualMachineInstanceSpecDomainFeaturesHypervTlbflush getTlbflush() {
    return tlbflush;
  }


  public void setTlbflush(V1alpha3VirtualMachineInstanceSpecDomainFeaturesHypervTlbflush tlbflush) {
    this.tlbflush = tlbflush;
  }


  public V1alpha3VirtualMachineInstanceSpecDomainFeaturesHyperv vapic(V1alpha3VirtualMachineInstanceSpecDomainFeaturesHypervVapic vapic) {
    
    this.vapic = vapic;
    return this;
  }

   /**
   * Get vapic
   * @return vapic
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha3VirtualMachineInstanceSpecDomainFeaturesHypervVapic getVapic() {
    return vapic;
  }


  public void setVapic(V1alpha3VirtualMachineInstanceSpecDomainFeaturesHypervVapic vapic) {
    this.vapic = vapic;
  }


  public V1alpha3VirtualMachineInstanceSpecDomainFeaturesHyperv vendorid(V1alpha3VirtualMachineInstanceSpecDomainFeaturesHypervVendorid vendorid) {
    
    this.vendorid = vendorid;
    return this;
  }

   /**
   * Get vendorid
   * @return vendorid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha3VirtualMachineInstanceSpecDomainFeaturesHypervVendorid getVendorid() {
    return vendorid;
  }


  public void setVendorid(V1alpha3VirtualMachineInstanceSpecDomainFeaturesHypervVendorid vendorid) {
    this.vendorid = vendorid;
  }


  public V1alpha3VirtualMachineInstanceSpecDomainFeaturesHyperv vpindex(V1alpha3VirtualMachineInstanceSpecDomainFeaturesHypervVpindex vpindex) {
    
    this.vpindex = vpindex;
    return this;
  }

   /**
   * Get vpindex
   * @return vpindex
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha3VirtualMachineInstanceSpecDomainFeaturesHypervVpindex getVpindex() {
    return vpindex;
  }


  public void setVpindex(V1alpha3VirtualMachineInstanceSpecDomainFeaturesHypervVpindex vpindex) {
    this.vpindex = vpindex;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha3VirtualMachineInstanceSpecDomainFeaturesHyperv v1alpha3VirtualMachineInstanceSpecDomainFeaturesHyperv = (V1alpha3VirtualMachineInstanceSpecDomainFeaturesHyperv) o;
    return Objects.equals(this.evmcs, v1alpha3VirtualMachineInstanceSpecDomainFeaturesHyperv.evmcs) &&
        Objects.equals(this.frequencies, v1alpha3VirtualMachineInstanceSpecDomainFeaturesHyperv.frequencies) &&
        Objects.equals(this.ipi, v1alpha3VirtualMachineInstanceSpecDomainFeaturesHyperv.ipi) &&
        Objects.equals(this.reenlightenment, v1alpha3VirtualMachineInstanceSpecDomainFeaturesHyperv.reenlightenment) &&
        Objects.equals(this.relaxed, v1alpha3VirtualMachineInstanceSpecDomainFeaturesHyperv.relaxed) &&
        Objects.equals(this.reset, v1alpha3VirtualMachineInstanceSpecDomainFeaturesHyperv.reset) &&
        Objects.equals(this.runtime, v1alpha3VirtualMachineInstanceSpecDomainFeaturesHyperv.runtime) &&
        Objects.equals(this.spinlocks, v1alpha3VirtualMachineInstanceSpecDomainFeaturesHyperv.spinlocks) &&
        Objects.equals(this.synic, v1alpha3VirtualMachineInstanceSpecDomainFeaturesHyperv.synic) &&
        Objects.equals(this.synictimer, v1alpha3VirtualMachineInstanceSpecDomainFeaturesHyperv.synictimer) &&
        Objects.equals(this.tlbflush, v1alpha3VirtualMachineInstanceSpecDomainFeaturesHyperv.tlbflush) &&
        Objects.equals(this.vapic, v1alpha3VirtualMachineInstanceSpecDomainFeaturesHyperv.vapic) &&
        Objects.equals(this.vendorid, v1alpha3VirtualMachineInstanceSpecDomainFeaturesHyperv.vendorid) &&
        Objects.equals(this.vpindex, v1alpha3VirtualMachineInstanceSpecDomainFeaturesHyperv.vpindex);
  }

  @Override
  public int hashCode() {
    return Objects.hash(evmcs, frequencies, ipi, reenlightenment, relaxed, reset, runtime, spinlocks, synic, synictimer, tlbflush, vapic, vendorid, vpindex);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha3VirtualMachineInstanceSpecDomainFeaturesHyperv {\n");
    sb.append("    evmcs: ").append(toIndentedString(evmcs)).append("\n");
    sb.append("    frequencies: ").append(toIndentedString(frequencies)).append("\n");
    sb.append("    ipi: ").append(toIndentedString(ipi)).append("\n");
    sb.append("    reenlightenment: ").append(toIndentedString(reenlightenment)).append("\n");
    sb.append("    relaxed: ").append(toIndentedString(relaxed)).append("\n");
    sb.append("    reset: ").append(toIndentedString(reset)).append("\n");
    sb.append("    runtime: ").append(toIndentedString(runtime)).append("\n");
    sb.append("    spinlocks: ").append(toIndentedString(spinlocks)).append("\n");
    sb.append("    synic: ").append(toIndentedString(synic)).append("\n");
    sb.append("    synictimer: ").append(toIndentedString(synictimer)).append("\n");
    sb.append("    tlbflush: ").append(toIndentedString(tlbflush)).append("\n");
    sb.append("    vapic: ").append(toIndentedString(vapic)).append("\n");
    sb.append("    vendorid: ").append(toIndentedString(vendorid)).append("\n");
    sb.append("    vpindex: ").append(toIndentedString(vpindex)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

