/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kubernetes.client.kubevirt.models;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;

/**
 * Devices allows adding disks, network interfaces, and others
 */
@ApiModel(description = "Devices allows adding disks, network interfaces, and others")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-11-29T01:55:00.032Z[Etc/UTC]")
public class V1alpha3VirtualMachineInstanceSpecDomainDevices {
  public static final String SERIALIZED_NAME_AUTOATTACH_GRAPHICS_DEVICE = "autoattachGraphicsDevice";
  @SerializedName(SERIALIZED_NAME_AUTOATTACH_GRAPHICS_DEVICE)
  private Boolean autoattachGraphicsDevice;

  public static final String SERIALIZED_NAME_AUTOATTACH_MEM_BALLOON = "autoattachMemBalloon";
  @SerializedName(SERIALIZED_NAME_AUTOATTACH_MEM_BALLOON)
  private Boolean autoattachMemBalloon;

  public static final String SERIALIZED_NAME_AUTOATTACH_POD_INTERFACE = "autoattachPodInterface";
  @SerializedName(SERIALIZED_NAME_AUTOATTACH_POD_INTERFACE)
  private Boolean autoattachPodInterface;

  public static final String SERIALIZED_NAME_AUTOATTACH_SERIAL_CONSOLE = "autoattachSerialConsole";
  @SerializedName(SERIALIZED_NAME_AUTOATTACH_SERIAL_CONSOLE)
  private Boolean autoattachSerialConsole;

  public static final String SERIALIZED_NAME_BLOCK_MULTI_QUEUE = "blockMultiQueue";
  @SerializedName(SERIALIZED_NAME_BLOCK_MULTI_QUEUE)
  private Boolean blockMultiQueue;

  public static final String SERIALIZED_NAME_DISKS = "disks";
  @SerializedName(SERIALIZED_NAME_DISKS)
  private List<V1alpha3VirtualMachineInstanceSpecDomainDevicesDisks> disks = null;

  public static final String SERIALIZED_NAME_FILESYSTEMS = "filesystems";
  @SerializedName(SERIALIZED_NAME_FILESYSTEMS)
  private List<V1alpha3VirtualMachineInstanceSpecDomainDevicesFilesystems> filesystems = null;

  public static final String SERIALIZED_NAME_GPUS = "gpus";
  @SerializedName(SERIALIZED_NAME_GPUS)
  private List<V1alpha3VirtualMachineInstanceSpecDomainDevicesGpus> gpus = null;

  public static final String SERIALIZED_NAME_INPUTS = "inputs";
  @SerializedName(SERIALIZED_NAME_INPUTS)
  private List<V1alpha3VirtualMachineInstanceSpecDomainDevicesInputs> inputs = null;

  public static final String SERIALIZED_NAME_INTERFACES = "interfaces";
  @SerializedName(SERIALIZED_NAME_INTERFACES)
  private List<V1alpha3VirtualMachineInstanceSpecDomainDevicesInterfaces> interfaces = null;

  public static final String SERIALIZED_NAME_NETWORK_INTERFACE_MULTIQUEUE = "networkInterfaceMultiqueue";
  @SerializedName(SERIALIZED_NAME_NETWORK_INTERFACE_MULTIQUEUE)
  private Boolean networkInterfaceMultiqueue;

  public static final String SERIALIZED_NAME_PCI_DEVICES = "pciDevices";
  @SerializedName(SERIALIZED_NAME_PCI_DEVICES)
  private List<V1alpha3VirtualMachineInstanceSpecDomainDevicesPciDevices> pciDevices = null;

  public static final String SERIALIZED_NAME_RNG = "rng";
  @SerializedName(SERIALIZED_NAME_RNG)
  private Object rng;

  public static final String SERIALIZED_NAME_WATCHDOG = "watchdog";
  @SerializedName(SERIALIZED_NAME_WATCHDOG)
  private V1alpha3VirtualMachineInstanceSpecDomainDevicesWatchdog watchdog;


  public V1alpha3VirtualMachineInstanceSpecDomainDevices autoattachGraphicsDevice(Boolean autoattachGraphicsDevice) {
    
    this.autoattachGraphicsDevice = autoattachGraphicsDevice;
    return this;
  }

   /**
   * Whether to attach the default graphics device or not. VNC will not be available if set to false. Defaults to true.
   * @return autoattachGraphicsDevice
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Whether to attach the default graphics device or not. VNC will not be available if set to false. Defaults to true.")

  public Boolean getAutoattachGraphicsDevice() {
    return autoattachGraphicsDevice;
  }


  public void setAutoattachGraphicsDevice(Boolean autoattachGraphicsDevice) {
    this.autoattachGraphicsDevice = autoattachGraphicsDevice;
  }


  public V1alpha3VirtualMachineInstanceSpecDomainDevices autoattachMemBalloon(Boolean autoattachMemBalloon) {
    
    this.autoattachMemBalloon = autoattachMemBalloon;
    return this;
  }

   /**
   * Whether to attach the Memory balloon device with default period. Period can be adjusted in virt-config. Defaults to true.
   * @return autoattachMemBalloon
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Whether to attach the Memory balloon device with default period. Period can be adjusted in virt-config. Defaults to true.")

  public Boolean getAutoattachMemBalloon() {
    return autoattachMemBalloon;
  }


  public void setAutoattachMemBalloon(Boolean autoattachMemBalloon) {
    this.autoattachMemBalloon = autoattachMemBalloon;
  }


  public V1alpha3VirtualMachineInstanceSpecDomainDevices autoattachPodInterface(Boolean autoattachPodInterface) {
    
    this.autoattachPodInterface = autoattachPodInterface;
    return this;
  }

   /**
   * Whether to attach a pod network interface. Defaults to true.
   * @return autoattachPodInterface
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Whether to attach a pod network interface. Defaults to true.")

  public Boolean getAutoattachPodInterface() {
    return autoattachPodInterface;
  }


  public void setAutoattachPodInterface(Boolean autoattachPodInterface) {
    this.autoattachPodInterface = autoattachPodInterface;
  }


  public V1alpha3VirtualMachineInstanceSpecDomainDevices autoattachSerialConsole(Boolean autoattachSerialConsole) {
    
    this.autoattachSerialConsole = autoattachSerialConsole;
    return this;
  }

   /**
   * Whether to attach the default serial console or not. Serial console access will not be available if set to false. Defaults to true.
   * @return autoattachSerialConsole
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Whether to attach the default serial console or not. Serial console access will not be available if set to false. Defaults to true.")

  public Boolean getAutoattachSerialConsole() {
    return autoattachSerialConsole;
  }


  public void setAutoattachSerialConsole(Boolean autoattachSerialConsole) {
    this.autoattachSerialConsole = autoattachSerialConsole;
  }


  public V1alpha3VirtualMachineInstanceSpecDomainDevices blockMultiQueue(Boolean blockMultiQueue) {
    
    this.blockMultiQueue = blockMultiQueue;
    return this;
  }

   /**
   * Whether or not to enable virtio multi-queue for block devices
   * @return blockMultiQueue
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Whether or not to enable virtio multi-queue for block devices")

  public Boolean getBlockMultiQueue() {
    return blockMultiQueue;
  }


  public void setBlockMultiQueue(Boolean blockMultiQueue) {
    this.blockMultiQueue = blockMultiQueue;
  }


  public V1alpha3VirtualMachineInstanceSpecDomainDevices disks(List<V1alpha3VirtualMachineInstanceSpecDomainDevicesDisks> disks) {
    
    this.disks = disks;
    return this;
  }

  public V1alpha3VirtualMachineInstanceSpecDomainDevices addDisksItem(V1alpha3VirtualMachineInstanceSpecDomainDevicesDisks disksItem) {
    if (this.disks == null) {
      this.disks = new ArrayList<>();
    }
    this.disks.add(disksItem);
    return this;
  }

   /**
   * Disks describes disks, cdroms, floppy and luns which are connected to the vmi.
   * @return disks
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Disks describes disks, cdroms, floppy and luns which are connected to the vmi.")

  public List<V1alpha3VirtualMachineInstanceSpecDomainDevicesDisks> getDisks() {
    return disks;
  }


  public void setDisks(List<V1alpha3VirtualMachineInstanceSpecDomainDevicesDisks> disks) {
    this.disks = disks;
  }


  public V1alpha3VirtualMachineInstanceSpecDomainDevices filesystems(List<V1alpha3VirtualMachineInstanceSpecDomainDevicesFilesystems> filesystems) {
    
    this.filesystems = filesystems;
    return this;
  }

  public V1alpha3VirtualMachineInstanceSpecDomainDevices addFilesystemsItem(V1alpha3VirtualMachineInstanceSpecDomainDevicesFilesystems filesystemsItem) {
    if (this.filesystems == null) {
      this.filesystems = new ArrayList<>();
    }
    this.filesystems.add(filesystemsItem);
    return this;
  }

   /**
   * Filesystems describes filesystem which is connected to the vmi.
   * @return filesystems
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Filesystems describes filesystem which is connected to the vmi.")

  public List<V1alpha3VirtualMachineInstanceSpecDomainDevicesFilesystems> getFilesystems() {
    return filesystems;
  }


  public void setFilesystems(List<V1alpha3VirtualMachineInstanceSpecDomainDevicesFilesystems> filesystems) {
    this.filesystems = filesystems;
  }


  public V1alpha3VirtualMachineInstanceSpecDomainDevices gpus(List<V1alpha3VirtualMachineInstanceSpecDomainDevicesGpus> gpus) {
    
    this.gpus = gpus;
    return this;
  }

  public V1alpha3VirtualMachineInstanceSpecDomainDevices addGpusItem(V1alpha3VirtualMachineInstanceSpecDomainDevicesGpus gpusItem) {
    if (this.gpus == null) {
      this.gpus = new ArrayList<>();
    }
    this.gpus.add(gpusItem);
    return this;
  }

   /**
   * Whether to attach a GPU device to the vmi.
   * @return gpus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Whether to attach a GPU device to the vmi.")

  public List<V1alpha3VirtualMachineInstanceSpecDomainDevicesGpus> getGpus() {
    return gpus;
  }


  public void setGpus(List<V1alpha3VirtualMachineInstanceSpecDomainDevicesGpus> gpus) {
    this.gpus = gpus;
  }


  public V1alpha3VirtualMachineInstanceSpecDomainDevices inputs(List<V1alpha3VirtualMachineInstanceSpecDomainDevicesInputs> inputs) {
    
    this.inputs = inputs;
    return this;
  }

  public V1alpha3VirtualMachineInstanceSpecDomainDevices addInputsItem(V1alpha3VirtualMachineInstanceSpecDomainDevicesInputs inputsItem) {
    if (this.inputs == null) {
      this.inputs = new ArrayList<>();
    }
    this.inputs.add(inputsItem);
    return this;
  }

   /**
   * Inputs describe input devices
   * @return inputs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Inputs describe input devices")

  public List<V1alpha3VirtualMachineInstanceSpecDomainDevicesInputs> getInputs() {
    return inputs;
  }


  public void setInputs(List<V1alpha3VirtualMachineInstanceSpecDomainDevicesInputs> inputs) {
    this.inputs = inputs;
  }


  public V1alpha3VirtualMachineInstanceSpecDomainDevices interfaces(List<V1alpha3VirtualMachineInstanceSpecDomainDevicesInterfaces> interfaces) {
    
    this.interfaces = interfaces;
    return this;
  }

  public V1alpha3VirtualMachineInstanceSpecDomainDevices addInterfacesItem(V1alpha3VirtualMachineInstanceSpecDomainDevicesInterfaces interfacesItem) {
    if (this.interfaces == null) {
      this.interfaces = new ArrayList<>();
    }
    this.interfaces.add(interfacesItem);
    return this;
  }

   /**
   * Interfaces describe network interfaces which are added to the vmi.
   * @return interfaces
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Interfaces describe network interfaces which are added to the vmi.")

  public List<V1alpha3VirtualMachineInstanceSpecDomainDevicesInterfaces> getInterfaces() {
    return interfaces;
  }


  public void setInterfaces(List<V1alpha3VirtualMachineInstanceSpecDomainDevicesInterfaces> interfaces) {
    this.interfaces = interfaces;
  }


  public V1alpha3VirtualMachineInstanceSpecDomainDevices networkInterfaceMultiqueue(Boolean networkInterfaceMultiqueue) {
    
    this.networkInterfaceMultiqueue = networkInterfaceMultiqueue;
    return this;
  }

   /**
   * If specified, virtual network interfaces configured with a virtio bus will also enable the vhost multiqueue feature for network devices. The number of queues created depends on additional factors of the VirtualMachineInstance, like the number of guest CPUs.
   * @return networkInterfaceMultiqueue
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "If specified, virtual network interfaces configured with a virtio bus will also enable the vhost multiqueue feature for network devices. The number of queues created depends on additional factors of the VirtualMachineInstance, like the number of guest CPUs.")

  public Boolean getNetworkInterfaceMultiqueue() {
    return networkInterfaceMultiqueue;
  }


  public void setNetworkInterfaceMultiqueue(Boolean networkInterfaceMultiqueue) {
    this.networkInterfaceMultiqueue = networkInterfaceMultiqueue;
  }


  public V1alpha3VirtualMachineInstanceSpecDomainDevices pciDevices(List<V1alpha3VirtualMachineInstanceSpecDomainDevicesPciDevices> pciDevices) {
    
    this.pciDevices = pciDevices;
    return this;
  }

  public V1alpha3VirtualMachineInstanceSpecDomainDevices addPciDevicesItem(V1alpha3VirtualMachineInstanceSpecDomainDevicesPciDevices pciDevicesItem) {
    if (this.pciDevices == null) {
      this.pciDevices = new ArrayList<>();
    }
    this.pciDevices.add(pciDevicesItem);
    return this;
  }

   /**
   * Whether to attach a PCI device to the vmi.
   * @return pciDevices
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Whether to attach a PCI device to the vmi.")

  public List<V1alpha3VirtualMachineInstanceSpecDomainDevicesPciDevices> getPciDevices() {
    return pciDevices;
  }


  public void setPciDevices(List<V1alpha3VirtualMachineInstanceSpecDomainDevicesPciDevices> pciDevices) {
    this.pciDevices = pciDevices;
  }


  public V1alpha3VirtualMachineInstanceSpecDomainDevices rng(Object rng) {
    
    this.rng = rng;
    return this;
  }

   /**
   * Whether to have random number generator from host
   * @return rng
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Whether to have random number generator from host")

  public Object getRng() {
    return rng;
  }


  public void setRng(Object rng) {
    this.rng = rng;
  }


  public V1alpha3VirtualMachineInstanceSpecDomainDevices watchdog(V1alpha3VirtualMachineInstanceSpecDomainDevicesWatchdog watchdog) {
    
    this.watchdog = watchdog;
    return this;
  }

   /**
   * Get watchdog
   * @return watchdog
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha3VirtualMachineInstanceSpecDomainDevicesWatchdog getWatchdog() {
    return watchdog;
  }


  public void setWatchdog(V1alpha3VirtualMachineInstanceSpecDomainDevicesWatchdog watchdog) {
    this.watchdog = watchdog;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha3VirtualMachineInstanceSpecDomainDevices v1alpha3VirtualMachineInstanceSpecDomainDevices = (V1alpha3VirtualMachineInstanceSpecDomainDevices) o;
    return Objects.equals(this.autoattachGraphicsDevice, v1alpha3VirtualMachineInstanceSpecDomainDevices.autoattachGraphicsDevice) &&
        Objects.equals(this.autoattachMemBalloon, v1alpha3VirtualMachineInstanceSpecDomainDevices.autoattachMemBalloon) &&
        Objects.equals(this.autoattachPodInterface, v1alpha3VirtualMachineInstanceSpecDomainDevices.autoattachPodInterface) &&
        Objects.equals(this.autoattachSerialConsole, v1alpha3VirtualMachineInstanceSpecDomainDevices.autoattachSerialConsole) &&
        Objects.equals(this.blockMultiQueue, v1alpha3VirtualMachineInstanceSpecDomainDevices.blockMultiQueue) &&
        Objects.equals(this.disks, v1alpha3VirtualMachineInstanceSpecDomainDevices.disks) &&
        Objects.equals(this.filesystems, v1alpha3VirtualMachineInstanceSpecDomainDevices.filesystems) &&
        Objects.equals(this.gpus, v1alpha3VirtualMachineInstanceSpecDomainDevices.gpus) &&
        Objects.equals(this.inputs, v1alpha3VirtualMachineInstanceSpecDomainDevices.inputs) &&
        Objects.equals(this.interfaces, v1alpha3VirtualMachineInstanceSpecDomainDevices.interfaces) &&
        Objects.equals(this.networkInterfaceMultiqueue, v1alpha3VirtualMachineInstanceSpecDomainDevices.networkInterfaceMultiqueue) &&
        Objects.equals(this.pciDevices, v1alpha3VirtualMachineInstanceSpecDomainDevices.pciDevices) &&
        Objects.equals(this.rng, v1alpha3VirtualMachineInstanceSpecDomainDevices.rng) &&
        Objects.equals(this.watchdog, v1alpha3VirtualMachineInstanceSpecDomainDevices.watchdog);
  }

  @Override
  public int hashCode() {
    return Objects.hash(autoattachGraphicsDevice, autoattachMemBalloon, autoattachPodInterface, autoattachSerialConsole, blockMultiQueue, disks, filesystems, gpus, inputs, interfaces, networkInterfaceMultiqueue, pciDevices, rng, watchdog);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha3VirtualMachineInstanceSpecDomainDevices {\n");
    sb.append("    autoattachGraphicsDevice: ").append(toIndentedString(autoattachGraphicsDevice)).append("\n");
    sb.append("    autoattachMemBalloon: ").append(toIndentedString(autoattachMemBalloon)).append("\n");
    sb.append("    autoattachPodInterface: ").append(toIndentedString(autoattachPodInterface)).append("\n");
    sb.append("    autoattachSerialConsole: ").append(toIndentedString(autoattachSerialConsole)).append("\n");
    sb.append("    blockMultiQueue: ").append(toIndentedString(blockMultiQueue)).append("\n");
    sb.append("    disks: ").append(toIndentedString(disks)).append("\n");
    sb.append("    filesystems: ").append(toIndentedString(filesystems)).append("\n");
    sb.append("    gpus: ").append(toIndentedString(gpus)).append("\n");
    sb.append("    inputs: ").append(toIndentedString(inputs)).append("\n");
    sb.append("    interfaces: ").append(toIndentedString(interfaces)).append("\n");
    sb.append("    networkInterfaceMultiqueue: ").append(toIndentedString(networkInterfaceMultiqueue)).append("\n");
    sb.append("    pciDevices: ").append(toIndentedString(pciDevices)).append("\n");
    sb.append("    rng: ").append(toIndentedString(rng)).append("\n");
    sb.append("    watchdog: ").append(toIndentedString(watchdog)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

