/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kubernetes.client.kubevirt.models;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * DHCPExtraOptions defines Extra DHCP options for a VM.
 */
@ApiModel(description = "DHCPExtraOptions defines Extra DHCP options for a VM.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-11-29T01:55:00.032Z[Etc/UTC]")
public class V1alpha3VirtualMachineInstanceSpecDomainDevicesDhcpOptionsPrivateOptions {
  public static final String SERIALIZED_NAME_OPTION = "option";
  @SerializedName(SERIALIZED_NAME_OPTION)
  private Integer option;

  public static final String SERIALIZED_NAME_VALUE = "value";
  @SerializedName(SERIALIZED_NAME_VALUE)
  private String value;


  public V1alpha3VirtualMachineInstanceSpecDomainDevicesDhcpOptionsPrivateOptions option(Integer option) {
    
    this.option = option;
    return this;
  }

   /**
   * Option is an Integer value from 224-254 Required.
   * @return option
  **/
  @ApiModelProperty(required = true, value = "Option is an Integer value from 224-254 Required.")

  public Integer getOption() {
    return option;
  }


  public void setOption(Integer option) {
    this.option = option;
  }


  public V1alpha3VirtualMachineInstanceSpecDomainDevicesDhcpOptionsPrivateOptions value(String value) {
    
    this.value = value;
    return this;
  }

   /**
   * Value is a String value for the Option provided Required.
   * @return value
  **/
  @ApiModelProperty(required = true, value = "Value is a String value for the Option provided Required.")

  public String getValue() {
    return value;
  }


  public void setValue(String value) {
    this.value = value;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha3VirtualMachineInstanceSpecDomainDevicesDhcpOptionsPrivateOptions v1alpha3VirtualMachineInstanceSpecDomainDevicesDhcpOptionsPrivateOptions = (V1alpha3VirtualMachineInstanceSpecDomainDevicesDhcpOptionsPrivateOptions) o;
    return Objects.equals(this.option, v1alpha3VirtualMachineInstanceSpecDomainDevicesDhcpOptionsPrivateOptions.option) &&
        Objects.equals(this.value, v1alpha3VirtualMachineInstanceSpecDomainDevicesDhcpOptionsPrivateOptions.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(option, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha3VirtualMachineInstanceSpecDomainDevicesDhcpOptionsPrivateOptions {\n");
    sb.append("    option: ").append(toIndentedString(option)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

