/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kubernetes.client.kubevirt.models;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Configure how KVM presence is exposed to the guest.
 */
@ApiModel(description = "Configure how KVM presence is exposed to the guest.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-11-29T01:55:00.032Z[Etc/UTC]")
public class V1alpha3VirtualMachineInstanceSpecDomainFeaturesKvm {
  public static final String SERIALIZED_NAME_HIDDEN = "hidden";
  @SerializedName(SERIALIZED_NAME_HIDDEN)
  private Boolean hidden;


  public V1alpha3VirtualMachineInstanceSpecDomainFeaturesKvm hidden(Boolean hidden) {
    
    this.hidden = hidden;
    return this;
  }

   /**
   * Hide the KVM hypervisor from standard MSR based discovery. Defaults to false
   * @return hidden
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Hide the KVM hypervisor from standard MSR based discovery. Defaults to false")

  public Boolean getHidden() {
    return hidden;
  }


  public void setHidden(Boolean hidden) {
    this.hidden = hidden;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha3VirtualMachineInstanceSpecDomainFeaturesKvm v1alpha3VirtualMachineInstanceSpecDomainFeaturesKvm = (V1alpha3VirtualMachineInstanceSpecDomainFeaturesKvm) o;
    return Objects.equals(this.hidden, v1alpha3VirtualMachineInstanceSpecDomainFeaturesKvm.hidden);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hidden);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha3VirtualMachineInstanceSpecDomainFeaturesKvm {\n");
    sb.append("    hidden: ").append(toIndentedString(hidden)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

