/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kubernetes.client.kubevirt.models;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Network represents a network type and a resource that should be connected to the vm.
 */
@ApiModel(description = "Network represents a network type and a resource that should be connected to the vm.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-11-29T01:55:00.032Z[Etc/UTC]")
public class V1alpha3VirtualMachineInstanceSpecNetworks {
  public static final String SERIALIZED_NAME_MULTUS = "multus";
  @SerializedName(SERIALIZED_NAME_MULTUS)
  private V1alpha3VirtualMachineInstanceSpecMultus multus;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_POD = "pod";
  @SerializedName(SERIALIZED_NAME_POD)
  private V1alpha3VirtualMachineInstanceSpecPod pod;


  public V1alpha3VirtualMachineInstanceSpecNetworks multus(V1alpha3VirtualMachineInstanceSpecMultus multus) {
    
    this.multus = multus;
    return this;
  }

   /**
   * Get multus
   * @return multus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha3VirtualMachineInstanceSpecMultus getMultus() {
    return multus;
  }


  public void setMultus(V1alpha3VirtualMachineInstanceSpecMultus multus) {
    this.multus = multus;
  }


  public V1alpha3VirtualMachineInstanceSpecNetworks name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Network name. Must be a DNS_LABEL and unique within the vm. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
   * @return name
  **/
  @ApiModelProperty(required = true, value = "Network name. Must be a DNS_LABEL and unique within the vm. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public V1alpha3VirtualMachineInstanceSpecNetworks pod(V1alpha3VirtualMachineInstanceSpecPod pod) {
    
    this.pod = pod;
    return this;
  }

   /**
   * Get pod
   * @return pod
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha3VirtualMachineInstanceSpecPod getPod() {
    return pod;
  }


  public void setPod(V1alpha3VirtualMachineInstanceSpecPod pod) {
    this.pod = pod;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha3VirtualMachineInstanceSpecNetworks v1alpha3VirtualMachineInstanceSpecNetworks = (V1alpha3VirtualMachineInstanceSpecNetworks) o;
    return Objects.equals(this.multus, v1alpha3VirtualMachineInstanceSpecNetworks.multus) &&
        Objects.equals(this.name, v1alpha3VirtualMachineInstanceSpecNetworks.name) &&
        Objects.equals(this.pod, v1alpha3VirtualMachineInstanceSpecNetworks.pod);
  }

  @Override
  public int hashCode() {
    return Objects.hash(multus, name, pod);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha3VirtualMachineInstanceSpecNetworks {\n");
    sb.append("    multus: ").append(toIndentedString(multus)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    pod: ").append(toIndentedString(pod)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

