/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kubernetes.client.kubevirt.models;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Memory allow specifying the VMI memory features.
 */
@ApiModel(description = "Memory allow specifying the VMI memory features.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-11-29T01:55:00.032Z[Etc/UTC]")
public class V1alpha3VirtualMachineInstanceSpecDomainMemory {
  public static final String SERIALIZED_NAME_GUEST = "guest";
  @SerializedName(SERIALIZED_NAME_GUEST)
  private Object guest;

  public static final String SERIALIZED_NAME_HUGEPAGES = "hugepages";
  @SerializedName(SERIALIZED_NAME_HUGEPAGES)
  private V1alpha3VirtualMachineInstanceSpecDomainMemoryHugepages hugepages;


  public V1alpha3VirtualMachineInstanceSpecDomainMemory guest(Object guest) {
    
    this.guest = guest;
    return this;
  }

   /**
   * Guest allows to specifying the amount of memory which is visible inside the Guest OS. The Guest must lie between Requests and Limits from the resources section. Defaults to the requested memory in the resources section if not specified.
   * @return guest
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Guest allows to specifying the amount of memory which is visible inside the Guest OS. The Guest must lie between Requests and Limits from the resources section. Defaults to the requested memory in the resources section if not specified.")

  public Object getGuest() {
    return guest;
  }


  public void setGuest(Object guest) {
    this.guest = guest;
  }


  public V1alpha3VirtualMachineInstanceSpecDomainMemory hugepages(V1alpha3VirtualMachineInstanceSpecDomainMemoryHugepages hugepages) {
    
    this.hugepages = hugepages;
    return this;
  }

   /**
   * Get hugepages
   * @return hugepages
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha3VirtualMachineInstanceSpecDomainMemoryHugepages getHugepages() {
    return hugepages;
  }


  public void setHugepages(V1alpha3VirtualMachineInstanceSpecDomainMemoryHugepages hugepages) {
    this.hugepages = hugepages;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha3VirtualMachineInstanceSpecDomainMemory v1alpha3VirtualMachineInstanceSpecDomainMemory = (V1alpha3VirtualMachineInstanceSpecDomainMemory) o;
    return Objects.equals(this.guest, v1alpha3VirtualMachineInstanceSpecDomainMemory.guest) &&
        Objects.equals(this.hugepages, v1alpha3VirtualMachineInstanceSpecDomainMemory.hugepages);
  }

  @Override
  public int hashCode() {
    return Objects.hash(guest, hugepages);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha3VirtualMachineInstanceSpecDomainMemory {\n");
    sb.append("    guest: ").append(toIndentedString(guest)).append("\n");
    sb.append("    hugepages: ").append(toIndentedString(hugepages)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

