/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kubernetes.client.kubevirt.models;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Watchdog describes a watchdog device which can be added to the vmi.
 */
@ApiModel(description = "Watchdog describes a watchdog device which can be added to the vmi.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-11-29T01:55:00.032Z[Etc/UTC]")
public class V1alpha3VirtualMachineInstanceSpecDomainDevicesWatchdog {
  public static final String SERIALIZED_NAME_I6300ESB = "i6300esb";
  @SerializedName(SERIALIZED_NAME_I6300ESB)
  private V1alpha3VirtualMachineInstanceSpecDomainDevicesWatchdogI6300esb i6300esb;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;


  public V1alpha3VirtualMachineInstanceSpecDomainDevicesWatchdog i6300esb(V1alpha3VirtualMachineInstanceSpecDomainDevicesWatchdogI6300esb i6300esb) {
    
    this.i6300esb = i6300esb;
    return this;
  }

   /**
   * Get i6300esb
   * @return i6300esb
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha3VirtualMachineInstanceSpecDomainDevicesWatchdogI6300esb getI6300esb() {
    return i6300esb;
  }


  public void setI6300esb(V1alpha3VirtualMachineInstanceSpecDomainDevicesWatchdogI6300esb i6300esb) {
    this.i6300esb = i6300esb;
  }


  public V1alpha3VirtualMachineInstanceSpecDomainDevicesWatchdog name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Name of the watchdog.
   * @return name
  **/
  @ApiModelProperty(required = true, value = "Name of the watchdog.")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha3VirtualMachineInstanceSpecDomainDevicesWatchdog v1alpha3VirtualMachineInstanceSpecDomainDevicesWatchdog = (V1alpha3VirtualMachineInstanceSpecDomainDevicesWatchdog) o;
    return Objects.equals(this.i6300esb, v1alpha3VirtualMachineInstanceSpecDomainDevicesWatchdog.i6300esb) &&
        Objects.equals(this.name, v1alpha3VirtualMachineInstanceSpecDomainDevicesWatchdog.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(i6300esb, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha3VirtualMachineInstanceSpecDomainDevicesWatchdog {\n");
    sb.append("    i6300esb: ").append(toIndentedString(i6300esb)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

