/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kubernetes.client.kubevirt.models;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Hugepages allow to use hugepages for the VirtualMachineInstance instead of regular memory.
 */
@ApiModel(description = "Hugepages allow to use hugepages for the VirtualMachineInstance instead of regular memory.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-11-29T01:55:00.032Z[Etc/UTC]")
public class V1alpha3VirtualMachineInstanceSpecDomainMemoryHugepages {
  public static final String SERIALIZED_NAME_PAGE_SIZE = "pageSize";
  @SerializedName(SERIALIZED_NAME_PAGE_SIZE)
  private String pageSize;


  public V1alpha3VirtualMachineInstanceSpecDomainMemoryHugepages pageSize(String pageSize) {
    
    this.pageSize = pageSize;
    return this;
  }

   /**
   * PageSize specifies the hugepage size, for x86_64 architecture valid values are 1Gi and 2Mi.
   * @return pageSize
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "PageSize specifies the hugepage size, for x86_64 architecture valid values are 1Gi and 2Mi.")

  public String getPageSize() {
    return pageSize;
  }


  public void setPageSize(String pageSize) {
    this.pageSize = pageSize;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha3VirtualMachineInstanceSpecDomainMemoryHugepages v1alpha3VirtualMachineInstanceSpecDomainMemoryHugepages = (V1alpha3VirtualMachineInstanceSpecDomainMemoryHugepages) o;
    return Objects.equals(this.pageSize, v1alpha3VirtualMachineInstanceSpecDomainMemoryHugepages.pageSize);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pageSize);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha3VirtualMachineInstanceSpecDomainMemoryHugepages {\n");
    sb.append("    pageSize: ").append(toIndentedString(pageSize)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

