/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kubernetes.client.kubevirt.models;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Volume represents a named volume in a vmi.
 */
@ApiModel(description = "Volume represents a named volume in a vmi.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-11-29T01:55:00.032Z[Etc/UTC]")
public class V1alpha3VirtualMachineInstanceSpecVolumes {
  public static final String SERIALIZED_NAME_CLOUD_INIT_CONFIG_DRIVE = "cloudInitConfigDrive";
  @SerializedName(SERIALIZED_NAME_CLOUD_INIT_CONFIG_DRIVE)
  private V1alpha3VirtualMachineInstanceSpecCloudInitConfigDrive cloudInitConfigDrive;

  public static final String SERIALIZED_NAME_CLOUD_INIT_NO_CLOUD = "cloudInitNoCloud";
  @SerializedName(SERIALIZED_NAME_CLOUD_INIT_NO_CLOUD)
  private V1alpha3VirtualMachineInstanceSpecCloudInitNoCloud cloudInitNoCloud;

  public static final String SERIALIZED_NAME_CONFIG_MAP = "configMap";
  @SerializedName(SERIALIZED_NAME_CONFIG_MAP)
  private V1alpha3VirtualMachineInstanceSpecConfigMap configMap;

  public static final String SERIALIZED_NAME_CONTAINER_DISK = "containerDisk";
  @SerializedName(SERIALIZED_NAME_CONTAINER_DISK)
  private V1alpha3VirtualMachineInstanceSpecContainerDisk containerDisk;

  public static final String SERIALIZED_NAME_DATA_VOLUME = "dataVolume";
  @SerializedName(SERIALIZED_NAME_DATA_VOLUME)
  private V1alpha3VirtualMachineInstanceSpecDataVolume dataVolume;

  public static final String SERIALIZED_NAME_DOWNWARD_A_P_I = "downwardAPI";
  @SerializedName(SERIALIZED_NAME_DOWNWARD_A_P_I)
  private V1alpha3VirtualMachineInstanceSpecDownwardAPI downwardAPI;

  public static final String SERIALIZED_NAME_EMPTY_DISK = "emptyDisk";
  @SerializedName(SERIALIZED_NAME_EMPTY_DISK)
  private V1alpha3VirtualMachineInstanceSpecEmptyDisk emptyDisk;

  public static final String SERIALIZED_NAME_EPHEMERAL = "ephemeral";
  @SerializedName(SERIALIZED_NAME_EPHEMERAL)
  private V1alpha3VirtualMachineInstanceSpecEphemeral ephemeral;

  public static final String SERIALIZED_NAME_HOST_DISK = "hostDisk";
  @SerializedName(SERIALIZED_NAME_HOST_DISK)
  private V1alpha3VirtualMachineInstanceSpecHostDisk hostDisk;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_PERSISTENT_VOLUME_CLAIM = "persistentVolumeClaim";
  @SerializedName(SERIALIZED_NAME_PERSISTENT_VOLUME_CLAIM)
  private V1alpha3VirtualMachineInstanceSpecEphemeralPersistentVolumeClaim persistentVolumeClaim;

  public static final String SERIALIZED_NAME_SECRET = "secret";
  @SerializedName(SERIALIZED_NAME_SECRET)
  private V1alpha3VirtualMachineInstanceSpecSecret secret;

  public static final String SERIALIZED_NAME_SERVICE_ACCOUNT = "serviceAccount";
  @SerializedName(SERIALIZED_NAME_SERVICE_ACCOUNT)
  private V1alpha3VirtualMachineInstanceSpecServiceAccount serviceAccount;


  public V1alpha3VirtualMachineInstanceSpecVolumes cloudInitConfigDrive(V1alpha3VirtualMachineInstanceSpecCloudInitConfigDrive cloudInitConfigDrive) {
    
    this.cloudInitConfigDrive = cloudInitConfigDrive;
    return this;
  }

   /**
   * Get cloudInitConfigDrive
   * @return cloudInitConfigDrive
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha3VirtualMachineInstanceSpecCloudInitConfigDrive getCloudInitConfigDrive() {
    return cloudInitConfigDrive;
  }


  public void setCloudInitConfigDrive(V1alpha3VirtualMachineInstanceSpecCloudInitConfigDrive cloudInitConfigDrive) {
    this.cloudInitConfigDrive = cloudInitConfigDrive;
  }


  public V1alpha3VirtualMachineInstanceSpecVolumes cloudInitNoCloud(V1alpha3VirtualMachineInstanceSpecCloudInitNoCloud cloudInitNoCloud) {
    
    this.cloudInitNoCloud = cloudInitNoCloud;
    return this;
  }

   /**
   * Get cloudInitNoCloud
   * @return cloudInitNoCloud
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha3VirtualMachineInstanceSpecCloudInitNoCloud getCloudInitNoCloud() {
    return cloudInitNoCloud;
  }


  public void setCloudInitNoCloud(V1alpha3VirtualMachineInstanceSpecCloudInitNoCloud cloudInitNoCloud) {
    this.cloudInitNoCloud = cloudInitNoCloud;
  }


  public V1alpha3VirtualMachineInstanceSpecVolumes configMap(V1alpha3VirtualMachineInstanceSpecConfigMap configMap) {
    
    this.configMap = configMap;
    return this;
  }

   /**
   * Get configMap
   * @return configMap
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha3VirtualMachineInstanceSpecConfigMap getConfigMap() {
    return configMap;
  }


  public void setConfigMap(V1alpha3VirtualMachineInstanceSpecConfigMap configMap) {
    this.configMap = configMap;
  }


  public V1alpha3VirtualMachineInstanceSpecVolumes containerDisk(V1alpha3VirtualMachineInstanceSpecContainerDisk containerDisk) {
    
    this.containerDisk = containerDisk;
    return this;
  }

   /**
   * Get containerDisk
   * @return containerDisk
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha3VirtualMachineInstanceSpecContainerDisk getContainerDisk() {
    return containerDisk;
  }


  public void setContainerDisk(V1alpha3VirtualMachineInstanceSpecContainerDisk containerDisk) {
    this.containerDisk = containerDisk;
  }


  public V1alpha3VirtualMachineInstanceSpecVolumes dataVolume(V1alpha3VirtualMachineInstanceSpecDataVolume dataVolume) {
    
    this.dataVolume = dataVolume;
    return this;
  }

   /**
   * Get dataVolume
   * @return dataVolume
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha3VirtualMachineInstanceSpecDataVolume getDataVolume() {
    return dataVolume;
  }


  public void setDataVolume(V1alpha3VirtualMachineInstanceSpecDataVolume dataVolume) {
    this.dataVolume = dataVolume;
  }


  public V1alpha3VirtualMachineInstanceSpecVolumes downwardAPI(V1alpha3VirtualMachineInstanceSpecDownwardAPI downwardAPI) {
    
    this.downwardAPI = downwardAPI;
    return this;
  }

   /**
   * Get downwardAPI
   * @return downwardAPI
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha3VirtualMachineInstanceSpecDownwardAPI getDownwardAPI() {
    return downwardAPI;
  }


  public void setDownwardAPI(V1alpha3VirtualMachineInstanceSpecDownwardAPI downwardAPI) {
    this.downwardAPI = downwardAPI;
  }


  public V1alpha3VirtualMachineInstanceSpecVolumes emptyDisk(V1alpha3VirtualMachineInstanceSpecEmptyDisk emptyDisk) {
    
    this.emptyDisk = emptyDisk;
    return this;
  }

   /**
   * Get emptyDisk
   * @return emptyDisk
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha3VirtualMachineInstanceSpecEmptyDisk getEmptyDisk() {
    return emptyDisk;
  }


  public void setEmptyDisk(V1alpha3VirtualMachineInstanceSpecEmptyDisk emptyDisk) {
    this.emptyDisk = emptyDisk;
  }


  public V1alpha3VirtualMachineInstanceSpecVolumes ephemeral(V1alpha3VirtualMachineInstanceSpecEphemeral ephemeral) {
    
    this.ephemeral = ephemeral;
    return this;
  }

   /**
   * Get ephemeral
   * @return ephemeral
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha3VirtualMachineInstanceSpecEphemeral getEphemeral() {
    return ephemeral;
  }


  public void setEphemeral(V1alpha3VirtualMachineInstanceSpecEphemeral ephemeral) {
    this.ephemeral = ephemeral;
  }


  public V1alpha3VirtualMachineInstanceSpecVolumes hostDisk(V1alpha3VirtualMachineInstanceSpecHostDisk hostDisk) {
    
    this.hostDisk = hostDisk;
    return this;
  }

   /**
   * Get hostDisk
   * @return hostDisk
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha3VirtualMachineInstanceSpecHostDisk getHostDisk() {
    return hostDisk;
  }


  public void setHostDisk(V1alpha3VirtualMachineInstanceSpecHostDisk hostDisk) {
    this.hostDisk = hostDisk;
  }


  public V1alpha3VirtualMachineInstanceSpecVolumes name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Volume&#39;s name. Must be a DNS_LABEL and unique within the vmi. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
   * @return name
  **/
  @ApiModelProperty(required = true, value = "Volume's name. Must be a DNS_LABEL and unique within the vmi. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public V1alpha3VirtualMachineInstanceSpecVolumes persistentVolumeClaim(V1alpha3VirtualMachineInstanceSpecEphemeralPersistentVolumeClaim persistentVolumeClaim) {
    
    this.persistentVolumeClaim = persistentVolumeClaim;
    return this;
  }

   /**
   * Get persistentVolumeClaim
   * @return persistentVolumeClaim
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha3VirtualMachineInstanceSpecEphemeralPersistentVolumeClaim getPersistentVolumeClaim() {
    return persistentVolumeClaim;
  }


  public void setPersistentVolumeClaim(V1alpha3VirtualMachineInstanceSpecEphemeralPersistentVolumeClaim persistentVolumeClaim) {
    this.persistentVolumeClaim = persistentVolumeClaim;
  }


  public V1alpha3VirtualMachineInstanceSpecVolumes secret(V1alpha3VirtualMachineInstanceSpecSecret secret) {
    
    this.secret = secret;
    return this;
  }

   /**
   * Get secret
   * @return secret
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha3VirtualMachineInstanceSpecSecret getSecret() {
    return secret;
  }


  public void setSecret(V1alpha3VirtualMachineInstanceSpecSecret secret) {
    this.secret = secret;
  }


  public V1alpha3VirtualMachineInstanceSpecVolumes serviceAccount(V1alpha3VirtualMachineInstanceSpecServiceAccount serviceAccount) {
    
    this.serviceAccount = serviceAccount;
    return this;
  }

   /**
   * Get serviceAccount
   * @return serviceAccount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha3VirtualMachineInstanceSpecServiceAccount getServiceAccount() {
    return serviceAccount;
  }


  public void setServiceAccount(V1alpha3VirtualMachineInstanceSpecServiceAccount serviceAccount) {
    this.serviceAccount = serviceAccount;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha3VirtualMachineInstanceSpecVolumes v1alpha3VirtualMachineInstanceSpecVolumes = (V1alpha3VirtualMachineInstanceSpecVolumes) o;
    return Objects.equals(this.cloudInitConfigDrive, v1alpha3VirtualMachineInstanceSpecVolumes.cloudInitConfigDrive) &&
        Objects.equals(this.cloudInitNoCloud, v1alpha3VirtualMachineInstanceSpecVolumes.cloudInitNoCloud) &&
        Objects.equals(this.configMap, v1alpha3VirtualMachineInstanceSpecVolumes.configMap) &&
        Objects.equals(this.containerDisk, v1alpha3VirtualMachineInstanceSpecVolumes.containerDisk) &&
        Objects.equals(this.dataVolume, v1alpha3VirtualMachineInstanceSpecVolumes.dataVolume) &&
        Objects.equals(this.downwardAPI, v1alpha3VirtualMachineInstanceSpecVolumes.downwardAPI) &&
        Objects.equals(this.emptyDisk, v1alpha3VirtualMachineInstanceSpecVolumes.emptyDisk) &&
        Objects.equals(this.ephemeral, v1alpha3VirtualMachineInstanceSpecVolumes.ephemeral) &&
        Objects.equals(this.hostDisk, v1alpha3VirtualMachineInstanceSpecVolumes.hostDisk) &&
        Objects.equals(this.name, v1alpha3VirtualMachineInstanceSpecVolumes.name) &&
        Objects.equals(this.persistentVolumeClaim, v1alpha3VirtualMachineInstanceSpecVolumes.persistentVolumeClaim) &&
        Objects.equals(this.secret, v1alpha3VirtualMachineInstanceSpecVolumes.secret) &&
        Objects.equals(this.serviceAccount, v1alpha3VirtualMachineInstanceSpecVolumes.serviceAccount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cloudInitConfigDrive, cloudInitNoCloud, configMap, containerDisk, dataVolume, downwardAPI, emptyDisk, ephemeral, hostDisk, name, persistentVolumeClaim, secret, serviceAccount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha3VirtualMachineInstanceSpecVolumes {\n");
    sb.append("    cloudInitConfigDrive: ").append(toIndentedString(cloudInitConfigDrive)).append("\n");
    sb.append("    cloudInitNoCloud: ").append(toIndentedString(cloudInitNoCloud)).append("\n");
    sb.append("    configMap: ").append(toIndentedString(configMap)).append("\n");
    sb.append("    containerDisk: ").append(toIndentedString(containerDisk)).append("\n");
    sb.append("    dataVolume: ").append(toIndentedString(dataVolume)).append("\n");
    sb.append("    downwardAPI: ").append(toIndentedString(downwardAPI)).append("\n");
    sb.append("    emptyDisk: ").append(toIndentedString(emptyDisk)).append("\n");
    sb.append("    ephemeral: ").append(toIndentedString(ephemeral)).append("\n");
    sb.append("    hostDisk: ").append(toIndentedString(hostDisk)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    persistentVolumeClaim: ").append(toIndentedString(persistentVolumeClaim)).append("\n");
    sb.append("    secret: ").append(toIndentedString(secret)).append("\n");
    sb.append("    serviceAccount: ").append(toIndentedString(serviceAccount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

