/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kubernetes.client.kubevirt.models;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * UTC sets the guest clock to UTC on each boot. If an offset is specified, guest changes to the clock will be kept during reboots and are not reset.
 */
@ApiModel(description = "UTC sets the guest clock to UTC on each boot. If an offset is specified, guest changes to the clock will be kept during reboots and are not reset.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-11-29T01:55:00.032Z[Etc/UTC]")
public class V1alpha3VirtualMachineInstanceSpecDomainClockUtc {
  public static final String SERIALIZED_NAME_OFFSET_SECONDS = "offsetSeconds";
  @SerializedName(SERIALIZED_NAME_OFFSET_SECONDS)
  private Integer offsetSeconds;


  public V1alpha3VirtualMachineInstanceSpecDomainClockUtc offsetSeconds(Integer offsetSeconds) {
    
    this.offsetSeconds = offsetSeconds;
    return this;
  }

   /**
   * OffsetSeconds specifies an offset in seconds, relative to UTC. If set, guest changes to the clock will be kept during reboots and not reset.
   * @return offsetSeconds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "OffsetSeconds specifies an offset in seconds, relative to UTC. If set, guest changes to the clock will be kept during reboots and not reset.")

  public Integer getOffsetSeconds() {
    return offsetSeconds;
  }


  public void setOffsetSeconds(Integer offsetSeconds) {
    this.offsetSeconds = offsetSeconds;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha3VirtualMachineInstanceSpecDomainClockUtc v1alpha3VirtualMachineInstanceSpecDomainClockUtc = (V1alpha3VirtualMachineInstanceSpecDomainClockUtc) o;
    return Objects.equals(this.offsetSeconds, v1alpha3VirtualMachineInstanceSpecDomainClockUtc.offsetSeconds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(offsetSeconds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha3VirtualMachineInstanceSpecDomainClockUtc {\n");
    sb.append("    offsetSeconds: ").append(toIndentedString(offsetSeconds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

