/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kubernetes.client.kubevirt.models;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * RTC (Real Time Clock) - a continuously running timer with periodic interrupts.
 */
@ApiModel(description = "RTC (Real Time Clock) - a continuously running timer with periodic interrupts.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-11-29T01:55:00.032Z[Etc/UTC]")
public class V1alpha3VirtualMachineInstanceSpecDomainClockTimerRtc {
  public static final String SERIALIZED_NAME_PRESENT = "present";
  @SerializedName(SERIALIZED_NAME_PRESENT)
  private Boolean present;

  public static final String SERIALIZED_NAME_TICK_POLICY = "tickPolicy";
  @SerializedName(SERIALIZED_NAME_TICK_POLICY)
  private String tickPolicy;

  public static final String SERIALIZED_NAME_TRACK = "track";
  @SerializedName(SERIALIZED_NAME_TRACK)
  private String track;


  public V1alpha3VirtualMachineInstanceSpecDomainClockTimerRtc present(Boolean present) {
    
    this.present = present;
    return this;
  }

   /**
   * Enabled set to false makes sure that the machine type or a preset can&#39;t add the timer. Defaults to true.
   * @return present
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Enabled set to false makes sure that the machine type or a preset can't add the timer. Defaults to true.")

  public Boolean getPresent() {
    return present;
  }


  public void setPresent(Boolean present) {
    this.present = present;
  }


  public V1alpha3VirtualMachineInstanceSpecDomainClockTimerRtc tickPolicy(String tickPolicy) {
    
    this.tickPolicy = tickPolicy;
    return this;
  }

   /**
   * TickPolicy determines what happens when QEMU misses a deadline for injecting a tick to the guest. One of \&quot;delay\&quot;, \&quot;catchup\&quot;.
   * @return tickPolicy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "TickPolicy determines what happens when QEMU misses a deadline for injecting a tick to the guest. One of \"delay\", \"catchup\".")

  public String getTickPolicy() {
    return tickPolicy;
  }


  public void setTickPolicy(String tickPolicy) {
    this.tickPolicy = tickPolicy;
  }


  public V1alpha3VirtualMachineInstanceSpecDomainClockTimerRtc track(String track) {
    
    this.track = track;
    return this;
  }

   /**
   * Track the guest or the wall clock.
   * @return track
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Track the guest or the wall clock.")

  public String getTrack() {
    return track;
  }


  public void setTrack(String track) {
    this.track = track;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha3VirtualMachineInstanceSpecDomainClockTimerRtc v1alpha3VirtualMachineInstanceSpecDomainClockTimerRtc = (V1alpha3VirtualMachineInstanceSpecDomainClockTimerRtc) o;
    return Objects.equals(this.present, v1alpha3VirtualMachineInstanceSpecDomainClockTimerRtc.present) &&
        Objects.equals(this.tickPolicy, v1alpha3VirtualMachineInstanceSpecDomainClockTimerRtc.tickPolicy) &&
        Objects.equals(this.track, v1alpha3VirtualMachineInstanceSpecDomainClockTimerRtc.track);
  }

  @Override
  public int hashCode() {
    return Objects.hash(present, tickPolicy, track);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha3VirtualMachineInstanceSpecDomainClockTimerRtc {\n");
    sb.append("    present: ").append(toIndentedString(present)).append("\n");
    sb.append("    tickPolicy: ").append(toIndentedString(tickPolicy)).append("\n");
    sb.append("    track: ").append(toIndentedString(track)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

