/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kubernetes.client.kubevirt.models;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Represents the stock pod network interface.
 */
@ApiModel(description = "Represents the stock pod network interface.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-11-29T01:55:00.032Z[Etc/UTC]")
public class V1alpha3VirtualMachineInstanceSpecPod {
  public static final String SERIALIZED_NAME_VM_NETWORK_C_I_D_R = "vmNetworkCIDR";
  @SerializedName(SERIALIZED_NAME_VM_NETWORK_C_I_D_R)
  private String vmNetworkCIDR;


  public V1alpha3VirtualMachineInstanceSpecPod vmNetworkCIDR(String vmNetworkCIDR) {
    
    this.vmNetworkCIDR = vmNetworkCIDR;
    return this;
  }

   /**
   * CIDR for vm network. Default 10.0.2.0/24 if not specified.
   * @return vmNetworkCIDR
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "CIDR for vm network. Default 10.0.2.0/24 if not specified.")

  public String getVmNetworkCIDR() {
    return vmNetworkCIDR;
  }


  public void setVmNetworkCIDR(String vmNetworkCIDR) {
    this.vmNetworkCIDR = vmNetworkCIDR;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha3VirtualMachineInstanceSpecPod v1alpha3VirtualMachineInstanceSpecPod = (V1alpha3VirtualMachineInstanceSpecPod) o;
    return Objects.equals(this.vmNetworkCIDR, v1alpha3VirtualMachineInstanceSpecPod.vmNetworkCIDR);
  }

  @Override
  public int hashCode() {
    return Objects.hash(vmNetworkCIDR);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha3VirtualMachineInstanceSpecPod {\n");
    sb.append("    vmNetworkCIDR: ").append(toIndentedString(vmNetworkCIDR)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

