/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kubernetes.client.kubevirt.models;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Spinlocks allows to configure the spinlock retry attempts.
 */
@ApiModel(description = "Spinlocks allows to configure the spinlock retry attempts.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-11-29T01:55:00.032Z[Etc/UTC]")
public class V1alpha3VirtualMachineInstanceSpecDomainFeaturesHypervSpinlocks {
  public static final String SERIALIZED_NAME_ENABLED = "enabled";
  @SerializedName(SERIALIZED_NAME_ENABLED)
  private Boolean enabled;

  public static final String SERIALIZED_NAME_SPINLOCKS = "spinlocks";
  @SerializedName(SERIALIZED_NAME_SPINLOCKS)
  private Integer spinlocks;


  public V1alpha3VirtualMachineInstanceSpecDomainFeaturesHypervSpinlocks enabled(Boolean enabled) {
    
    this.enabled = enabled;
    return this;
  }

   /**
   * Enabled determines if the feature should be enabled or disabled on the guest. Defaults to true.
   * @return enabled
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Enabled determines if the feature should be enabled or disabled on the guest. Defaults to true.")

  public Boolean getEnabled() {
    return enabled;
  }


  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }


  public V1alpha3VirtualMachineInstanceSpecDomainFeaturesHypervSpinlocks spinlocks(Integer spinlocks) {
    
    this.spinlocks = spinlocks;
    return this;
  }

   /**
   * Retries indicates the number of retries. Must be a value greater or equal 4096. Defaults to 4096.
   * @return spinlocks
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Retries indicates the number of retries. Must be a value greater or equal 4096. Defaults to 4096.")

  public Integer getSpinlocks() {
    return spinlocks;
  }


  public void setSpinlocks(Integer spinlocks) {
    this.spinlocks = spinlocks;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha3VirtualMachineInstanceSpecDomainFeaturesHypervSpinlocks v1alpha3VirtualMachineInstanceSpecDomainFeaturesHypervSpinlocks = (V1alpha3VirtualMachineInstanceSpecDomainFeaturesHypervSpinlocks) o;
    return Objects.equals(this.enabled, v1alpha3VirtualMachineInstanceSpecDomainFeaturesHypervSpinlocks.enabled) &&
        Objects.equals(this.spinlocks, v1alpha3VirtualMachineInstanceSpecDomainFeaturesHypervSpinlocks.spinlocks);
  }

  @Override
  public int hashCode() {
    return Objects.hash(enabled, spinlocks);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha3VirtualMachineInstanceSpecDomainFeaturesHypervSpinlocks {\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    spinlocks: ").append(toIndentedString(spinlocks)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

