/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kubernetes.client.kubevirt.models;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.time.OffsetDateTime;

/**
 * VirtualMachineInstancePhaseTransitionTimestamp gives a timestamp in relation to when a phase is set on a vmi
 */
@ApiModel(description = "VirtualMachineInstancePhaseTransitionTimestamp gives a timestamp in relation to when a phase is set on a vmi")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-11-29T01:55:00.032Z[Etc/UTC]")
public class V1alpha3VirtualMachineInstanceStatusPhaseTransitionTimestamps {
  public static final String SERIALIZED_NAME_PHASE = "phase";
  @SerializedName(SERIALIZED_NAME_PHASE)
  private String phase;

  public static final String SERIALIZED_NAME_PHASE_TRANSITION_TIMESTAMP = "phaseTransitionTimestamp";
  @SerializedName(SERIALIZED_NAME_PHASE_TRANSITION_TIMESTAMP)
  private OffsetDateTime phaseTransitionTimestamp;


  public V1alpha3VirtualMachineInstanceStatusPhaseTransitionTimestamps phase(String phase) {
    
    this.phase = phase;
    return this;
  }

   /**
   * Phase is the status of the VirtualMachineInstance in kubernetes world. It is not the VirtualMachineInstance status, but partially correlates to it.
   * @return phase
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Phase is the status of the VirtualMachineInstance in kubernetes world. It is not the VirtualMachineInstance status, but partially correlates to it.")

  public String getPhase() {
    return phase;
  }


  public void setPhase(String phase) {
    this.phase = phase;
  }


  public V1alpha3VirtualMachineInstanceStatusPhaseTransitionTimestamps phaseTransitionTimestamp(OffsetDateTime phaseTransitionTimestamp) {
    
    this.phaseTransitionTimestamp = phaseTransitionTimestamp;
    return this;
  }

   /**
   * PhaseTransitionTimestamp is the timestamp of when the phase change occurred
   * @return phaseTransitionTimestamp
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "PhaseTransitionTimestamp is the timestamp of when the phase change occurred")

  public OffsetDateTime getPhaseTransitionTimestamp() {
    return phaseTransitionTimestamp;
  }


  public void setPhaseTransitionTimestamp(OffsetDateTime phaseTransitionTimestamp) {
    this.phaseTransitionTimestamp = phaseTransitionTimestamp;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha3VirtualMachineInstanceStatusPhaseTransitionTimestamps v1alpha3VirtualMachineInstanceStatusPhaseTransitionTimestamps = (V1alpha3VirtualMachineInstanceStatusPhaseTransitionTimestamps) o;
    return Objects.equals(this.phase, v1alpha3VirtualMachineInstanceStatusPhaseTransitionTimestamps.phase) &&
        Objects.equals(this.phaseTransitionTimestamp, v1alpha3VirtualMachineInstanceStatusPhaseTransitionTimestamps.phaseTransitionTimestamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(phase, phaseTransitionTimestamp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha3VirtualMachineInstanceStatusPhaseTransitionTimestamps {\n");
    sb.append("    phase: ").append(toIndentedString(phase)).append("\n");
    sb.append("    phaseTransitionTimestamp: ").append(toIndentedString(phaseTransitionTimestamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

