/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kubernetes.client.kubevirt.models;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Timer specifies whih timers are attached to the vmi.
 */
@ApiModel(description = "Timer specifies whih timers are attached to the vmi.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-11-29T01:55:00.032Z[Etc/UTC]")
public class V1alpha3VirtualMachineInstanceSpecDomainClockTimer {
  public static final String SERIALIZED_NAME_HPET = "hpet";
  @SerializedName(SERIALIZED_NAME_HPET)
  private V1alpha3VirtualMachineInstanceSpecDomainClockTimerHpet hpet;

  public static final String SERIALIZED_NAME_HYPERV = "hyperv";
  @SerializedName(SERIALIZED_NAME_HYPERV)
  private V1alpha3VirtualMachineInstanceSpecDomainClockTimerHyperv hyperv;

  public static final String SERIALIZED_NAME_KVM = "kvm";
  @SerializedName(SERIALIZED_NAME_KVM)
  private V1alpha3VirtualMachineInstanceSpecDomainClockTimerKvm kvm;

  public static final String SERIALIZED_NAME_PIT = "pit";
  @SerializedName(SERIALIZED_NAME_PIT)
  private V1alpha3VirtualMachineInstanceSpecDomainClockTimerPit pit;

  public static final String SERIALIZED_NAME_RTC = "rtc";
  @SerializedName(SERIALIZED_NAME_RTC)
  private V1alpha3VirtualMachineInstanceSpecDomainClockTimerRtc rtc;


  public V1alpha3VirtualMachineInstanceSpecDomainClockTimer hpet(V1alpha3VirtualMachineInstanceSpecDomainClockTimerHpet hpet) {
    
    this.hpet = hpet;
    return this;
  }

   /**
   * Get hpet
   * @return hpet
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha3VirtualMachineInstanceSpecDomainClockTimerHpet getHpet() {
    return hpet;
  }


  public void setHpet(V1alpha3VirtualMachineInstanceSpecDomainClockTimerHpet hpet) {
    this.hpet = hpet;
  }


  public V1alpha3VirtualMachineInstanceSpecDomainClockTimer hyperv(V1alpha3VirtualMachineInstanceSpecDomainClockTimerHyperv hyperv) {
    
    this.hyperv = hyperv;
    return this;
  }

   /**
   * Get hyperv
   * @return hyperv
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha3VirtualMachineInstanceSpecDomainClockTimerHyperv getHyperv() {
    return hyperv;
  }


  public void setHyperv(V1alpha3VirtualMachineInstanceSpecDomainClockTimerHyperv hyperv) {
    this.hyperv = hyperv;
  }


  public V1alpha3VirtualMachineInstanceSpecDomainClockTimer kvm(V1alpha3VirtualMachineInstanceSpecDomainClockTimerKvm kvm) {
    
    this.kvm = kvm;
    return this;
  }

   /**
   * Get kvm
   * @return kvm
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha3VirtualMachineInstanceSpecDomainClockTimerKvm getKvm() {
    return kvm;
  }


  public void setKvm(V1alpha3VirtualMachineInstanceSpecDomainClockTimerKvm kvm) {
    this.kvm = kvm;
  }


  public V1alpha3VirtualMachineInstanceSpecDomainClockTimer pit(V1alpha3VirtualMachineInstanceSpecDomainClockTimerPit pit) {
    
    this.pit = pit;
    return this;
  }

   /**
   * Get pit
   * @return pit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha3VirtualMachineInstanceSpecDomainClockTimerPit getPit() {
    return pit;
  }


  public void setPit(V1alpha3VirtualMachineInstanceSpecDomainClockTimerPit pit) {
    this.pit = pit;
  }


  public V1alpha3VirtualMachineInstanceSpecDomainClockTimer rtc(V1alpha3VirtualMachineInstanceSpecDomainClockTimerRtc rtc) {
    
    this.rtc = rtc;
    return this;
  }

   /**
   * Get rtc
   * @return rtc
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha3VirtualMachineInstanceSpecDomainClockTimerRtc getRtc() {
    return rtc;
  }


  public void setRtc(V1alpha3VirtualMachineInstanceSpecDomainClockTimerRtc rtc) {
    this.rtc = rtc;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha3VirtualMachineInstanceSpecDomainClockTimer v1alpha3VirtualMachineInstanceSpecDomainClockTimer = (V1alpha3VirtualMachineInstanceSpecDomainClockTimer) o;
    return Objects.equals(this.hpet, v1alpha3VirtualMachineInstanceSpecDomainClockTimer.hpet) &&
        Objects.equals(this.hyperv, v1alpha3VirtualMachineInstanceSpecDomainClockTimer.hyperv) &&
        Objects.equals(this.kvm, v1alpha3VirtualMachineInstanceSpecDomainClockTimer.kvm) &&
        Objects.equals(this.pit, v1alpha3VirtualMachineInstanceSpecDomainClockTimer.pit) &&
        Objects.equals(this.rtc, v1alpha3VirtualMachineInstanceSpecDomainClockTimer.rtc);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hpet, hyperv, kvm, pit, rtc);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha3VirtualMachineInstanceSpecDomainClockTimer {\n");
    sb.append("    hpet: ").append(toIndentedString(hpet)).append("\n");
    sb.append("    hyperv: ").append(toIndentedString(hyperv)).append("\n");
    sb.append("    kvm: ").append(toIndentedString(kvm)).append("\n");
    sb.append("    pit: ").append(toIndentedString(pit)).append("\n");
    sb.append("    rtc: ").append(toIndentedString(rtc)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

