/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kubernetes.client.kubevirt.models;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;

/**
 * V1alpha3VirtualMachineInstanceStatusInterfaces
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-11-29T01:55:00.032Z[Etc/UTC]")
public class V1alpha3VirtualMachineInstanceStatusInterfaces {
  public static final String SERIALIZED_NAME_INTERFACE_NAME = "interfaceName";
  @SerializedName(SERIALIZED_NAME_INTERFACE_NAME)
  private String interfaceName;

  public static final String SERIALIZED_NAME_IP_ADDRESS = "ipAddress";
  @SerializedName(SERIALIZED_NAME_IP_ADDRESS)
  private String ipAddress;

  public static final String SERIALIZED_NAME_IP_ADDRESSES = "ipAddresses";
  @SerializedName(SERIALIZED_NAME_IP_ADDRESSES)
  private List<String> ipAddresses = null;

  public static final String SERIALIZED_NAME_MAC = "mac";
  @SerializedName(SERIALIZED_NAME_MAC)
  private String mac;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;


  public V1alpha3VirtualMachineInstanceStatusInterfaces interfaceName(String interfaceName) {
    
    this.interfaceName = interfaceName;
    return this;
  }

   /**
   * The interface name inside the Virtual Machine
   * @return interfaceName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The interface name inside the Virtual Machine")

  public String getInterfaceName() {
    return interfaceName;
  }


  public void setInterfaceName(String interfaceName) {
    this.interfaceName = interfaceName;
  }


  public V1alpha3VirtualMachineInstanceStatusInterfaces ipAddress(String ipAddress) {
    
    this.ipAddress = ipAddress;
    return this;
  }

   /**
   * IP address of a Virtual Machine interface. It is always the first item of IPs
   * @return ipAddress
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "IP address of a Virtual Machine interface. It is always the first item of IPs")

  public String getIpAddress() {
    return ipAddress;
  }


  public void setIpAddress(String ipAddress) {
    this.ipAddress = ipAddress;
  }


  public V1alpha3VirtualMachineInstanceStatusInterfaces ipAddresses(List<String> ipAddresses) {
    
    this.ipAddresses = ipAddresses;
    return this;
  }

  public V1alpha3VirtualMachineInstanceStatusInterfaces addIpAddressesItem(String ipAddressesItem) {
    if (this.ipAddresses == null) {
      this.ipAddresses = new ArrayList<>();
    }
    this.ipAddresses.add(ipAddressesItem);
    return this;
  }

   /**
   * List of all IP addresses of a Virtual Machine interface
   * @return ipAddresses
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "List of all IP addresses of a Virtual Machine interface")

  public List<String> getIpAddresses() {
    return ipAddresses;
  }


  public void setIpAddresses(List<String> ipAddresses) {
    this.ipAddresses = ipAddresses;
  }


  public V1alpha3VirtualMachineInstanceStatusInterfaces mac(String mac) {
    
    this.mac = mac;
    return this;
  }

   /**
   * Hardware address of a Virtual Machine interface
   * @return mac
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Hardware address of a Virtual Machine interface")

  public String getMac() {
    return mac;
  }


  public void setMac(String mac) {
    this.mac = mac;
  }


  public V1alpha3VirtualMachineInstanceStatusInterfaces name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Name of the interface, corresponds to name of the network assigned to the interface TODO: remove omitempty, when api breaking changes are allowed
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Name of the interface, corresponds to name of the network assigned to the interface TODO: remove omitempty, when api breaking changes are allowed")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha3VirtualMachineInstanceStatusInterfaces v1alpha3VirtualMachineInstanceStatusInterfaces = (V1alpha3VirtualMachineInstanceStatusInterfaces) o;
    return Objects.equals(this.interfaceName, v1alpha3VirtualMachineInstanceStatusInterfaces.interfaceName) &&
        Objects.equals(this.ipAddress, v1alpha3VirtualMachineInstanceStatusInterfaces.ipAddress) &&
        Objects.equals(this.ipAddresses, v1alpha3VirtualMachineInstanceStatusInterfaces.ipAddresses) &&
        Objects.equals(this.mac, v1alpha3VirtualMachineInstanceStatusInterfaces.mac) &&
        Objects.equals(this.name, v1alpha3VirtualMachineInstanceStatusInterfaces.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(interfaceName, ipAddress, ipAddresses, mac, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha3VirtualMachineInstanceStatusInterfaces {\n");
    sb.append("    interfaceName: ").append(toIndentedString(interfaceName)).append("\n");
    sb.append("    ipAddress: ").append(toIndentedString(ipAddress)).append("\n");
    sb.append("    ipAddresses: ").append(toIndentedString(ipAddresses)).append("\n");
    sb.append("    mac: ").append(toIndentedString(mac)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

